// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: python3_10.proto

package com.giyeok.tython.proto;

public interface AbstractUnaryopOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.giyeok.tython.proto.AbstractUnaryop)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.giyeok.tython.proto.Invert invert = 1;</code>
   * @return Whether the invert field is set.
   */
  boolean hasInvert();
  /**
   * <code>.com.giyeok.tython.proto.Invert invert = 1;</code>
   * @return The invert.
   */
  com.giyeok.tython.proto.Invert getInvert();
  /**
   * <code>.com.giyeok.tython.proto.Invert invert = 1;</code>
   */
  com.giyeok.tython.proto.InvertOrBuilder getInvertOrBuilder();

  /**
   * <code>.com.giyeok.tython.proto.Not not = 2;</code>
   * @return Whether the not field is set.
   */
  boolean hasNot();
  /**
   * <code>.com.giyeok.tython.proto.Not not = 2;</code>
   * @return The not.
   */
  com.giyeok.tython.proto.Not getNot();
  /**
   * <code>.com.giyeok.tython.proto.Not not = 2;</code>
   */
  com.giyeok.tython.proto.NotOrBuilder getNotOrBuilder();

  /**
   * <code>.com.giyeok.tython.proto.UAdd u_add = 3;</code>
   * @return Whether the uAdd field is set.
   */
  boolean hasUAdd();
  /**
   * <code>.com.giyeok.tython.proto.UAdd u_add = 3;</code>
   * @return The uAdd.
   */
  com.giyeok.tython.proto.UAdd getUAdd();
  /**
   * <code>.com.giyeok.tython.proto.UAdd u_add = 3;</code>
   */
  com.giyeok.tython.proto.UAddOrBuilder getUAddOrBuilder();

  /**
   * <code>.com.giyeok.tython.proto.USub u_sub = 4;</code>
   * @return Whether the uSub field is set.
   */
  boolean hasUSub();
  /**
   * <code>.com.giyeok.tython.proto.USub u_sub = 4;</code>
   * @return The uSub.
   */
  com.giyeok.tython.proto.USub getUSub();
  /**
   * <code>.com.giyeok.tython.proto.USub u_sub = 4;</code>
   */
  com.giyeok.tython.proto.USubOrBuilder getUSubOrBuilder();

  public com.giyeok.tython.proto.AbstractUnaryop.AbstractUnaryopCase getAbstractUnaryopCase();
}
