// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: python3_10.proto

package com.giyeok.tython.proto;

public interface AbstractBoolopOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.giyeok.tython.proto.AbstractBoolop)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.giyeok.tython.proto.And and = 1;</code>
   * @return Whether the and field is set.
   */
  boolean hasAnd();
  /**
   * <code>.com.giyeok.tython.proto.And and = 1;</code>
   * @return The and.
   */
  com.giyeok.tython.proto.And getAnd();
  /**
   * <code>.com.giyeok.tython.proto.And and = 1;</code>
   */
  com.giyeok.tython.proto.AndOrBuilder getAndOrBuilder();

  /**
   * <code>.com.giyeok.tython.proto.Or or = 2;</code>
   * @return Whether the or field is set.
   */
  boolean hasOr();
  /**
   * <code>.com.giyeok.tython.proto.Or or = 2;</code>
   * @return The or.
   */
  com.giyeok.tython.proto.Or getOr();
  /**
   * <code>.com.giyeok.tython.proto.Or or = 2;</code>
   */
  com.giyeok.tython.proto.OrOrBuilder getOrOrBuilder();

  public com.giyeok.tython.proto.AbstractBoolop.AbstractBoolopCase getAbstractBoolopCase();
}
