// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: python3_10.proto

package com.giyeok.tython.proto;

public interface AbstractExcepthandlerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.giyeok.tython.proto.AbstractExcepthandler)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.giyeok.tython.proto.ExceptHandler except_handler = 1;</code>
   * @return Whether the exceptHandler field is set.
   */
  boolean hasExceptHandler();
  /**
   * <code>.com.giyeok.tython.proto.ExceptHandler except_handler = 1;</code>
   * @return The exceptHandler.
   */
  com.giyeok.tython.proto.ExceptHandler getExceptHandler();
  /**
   * <code>.com.giyeok.tython.proto.ExceptHandler except_handler = 1;</code>
   */
  com.giyeok.tython.proto.ExceptHandlerOrBuilder getExceptHandlerOrBuilder();

  public com.giyeok.tython.proto.AbstractExcepthandler.AbstractExcepthandlerCase getAbstractExcepthandlerCase();
}
