// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: python3_10.proto

package com.giyeok.tython.proto;

/**
 * Protobuf type {@code com.giyeok.tython.proto.Arg}
 */
public final class Arg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.giyeok.tython.proto.Arg)
    ArgOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Arg.newBuilder() to construct.
  private Arg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Arg() {
    arg_ = "";
    typeComment_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Arg();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Arg(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            arg_ = s;
            break;
          }
          case 18: {
            com.giyeok.tython.proto.AbstractExpr.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = annotation_.toBuilder();
            }
            annotation_ = input.readMessage(com.giyeok.tython.proto.AbstractExpr.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(annotation_);
              annotation_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000002;
            typeComment_ = s;
            break;
          }
          case 32: {

            lineno_ = input.readInt32();
            break;
          }
          case 40: {

            colOffset_ = input.readInt32();
            break;
          }
          case 48: {
            bitField0_ |= 0x00000004;
            endLineno_ = input.readInt32();
            break;
          }
          case 56: {
            bitField0_ |= 0x00000008;
            endColOffset_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_Arg_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_Arg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.giyeok.tython.proto.Arg.class, com.giyeok.tython.proto.Arg.Builder.class);
  }

  private int bitField0_;
  public static final int ARG_FIELD_NUMBER = 1;
  private volatile java.lang.Object arg_;
  /**
   * <code>string arg = 1;</code>
   * @return The arg.
   */
  @java.lang.Override
  public java.lang.String getArg() {
    java.lang.Object ref = arg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      arg_ = s;
      return s;
    }
  }
  /**
   * <code>string arg = 1;</code>
   * @return The bytes for arg.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getArgBytes() {
    java.lang.Object ref = arg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      arg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ANNOTATION_FIELD_NUMBER = 2;
  private com.giyeok.tython.proto.AbstractExpr annotation_;
  /**
   * <code>optional .com.giyeok.tython.proto.AbstractExpr annotation = 2;</code>
   * @return Whether the annotation field is set.
   */
  @java.lang.Override
  public boolean hasAnnotation() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .com.giyeok.tython.proto.AbstractExpr annotation = 2;</code>
   * @return The annotation.
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractExpr getAnnotation() {
    return annotation_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : annotation_;
  }
  /**
   * <code>optional .com.giyeok.tython.proto.AbstractExpr annotation = 2;</code>
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractExprOrBuilder getAnnotationOrBuilder() {
    return annotation_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : annotation_;
  }

  public static final int TYPE_COMMENT_FIELD_NUMBER = 3;
  private volatile java.lang.Object typeComment_;
  /**
   * <code>optional string type_comment = 3;</code>
   * @return Whether the typeComment field is set.
   */
  @java.lang.Override
  public boolean hasTypeComment() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string type_comment = 3;</code>
   * @return The typeComment.
   */
  @java.lang.Override
  public java.lang.String getTypeComment() {
    java.lang.Object ref = typeComment_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      typeComment_ = s;
      return s;
    }
  }
  /**
   * <code>optional string type_comment = 3;</code>
   * @return The bytes for typeComment.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeCommentBytes() {
    java.lang.Object ref = typeComment_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      typeComment_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LINENO_FIELD_NUMBER = 4;
  private int lineno_;
  /**
   * <code>int32 lineno = 4;</code>
   * @return The lineno.
   */
  @java.lang.Override
  public int getLineno() {
    return lineno_;
  }

  public static final int COL_OFFSET_FIELD_NUMBER = 5;
  private int colOffset_;
  /**
   * <code>int32 col_offset = 5;</code>
   * @return The colOffset.
   */
  @java.lang.Override
  public int getColOffset() {
    return colOffset_;
  }

  public static final int END_LINENO_FIELD_NUMBER = 6;
  private int endLineno_;
  /**
   * <code>optional int32 end_lineno = 6;</code>
   * @return Whether the endLineno field is set.
   */
  @java.lang.Override
  public boolean hasEndLineno() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int32 end_lineno = 6;</code>
   * @return The endLineno.
   */
  @java.lang.Override
  public int getEndLineno() {
    return endLineno_;
  }

  public static final int END_COL_OFFSET_FIELD_NUMBER = 7;
  private int endColOffset_;
  /**
   * <code>optional int32 end_col_offset = 7;</code>
   * @return Whether the endColOffset field is set.
   */
  @java.lang.Override
  public boolean hasEndColOffset() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional int32 end_col_offset = 7;</code>
   * @return The endColOffset.
   */
  @java.lang.Override
  public int getEndColOffset() {
    return endColOffset_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(arg_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, arg_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getAnnotation());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, typeComment_);
    }
    if (lineno_ != 0) {
      output.writeInt32(4, lineno_);
    }
    if (colOffset_ != 0) {
      output.writeInt32(5, colOffset_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(6, endLineno_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt32(7, endColOffset_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(arg_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, arg_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAnnotation());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, typeComment_);
    }
    if (lineno_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, lineno_);
    }
    if (colOffset_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, colOffset_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, endLineno_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, endColOffset_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.giyeok.tython.proto.Arg)) {
      return super.equals(obj);
    }
    com.giyeok.tython.proto.Arg other = (com.giyeok.tython.proto.Arg) obj;

    if (!getArg()
        .equals(other.getArg())) return false;
    if (hasAnnotation() != other.hasAnnotation()) return false;
    if (hasAnnotation()) {
      if (!getAnnotation()
          .equals(other.getAnnotation())) return false;
    }
    if (hasTypeComment() != other.hasTypeComment()) return false;
    if (hasTypeComment()) {
      if (!getTypeComment()
          .equals(other.getTypeComment())) return false;
    }
    if (getLineno()
        != other.getLineno()) return false;
    if (getColOffset()
        != other.getColOffset()) return false;
    if (hasEndLineno() != other.hasEndLineno()) return false;
    if (hasEndLineno()) {
      if (getEndLineno()
          != other.getEndLineno()) return false;
    }
    if (hasEndColOffset() != other.hasEndColOffset()) return false;
    if (hasEndColOffset()) {
      if (getEndColOffset()
          != other.getEndColOffset()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ARG_FIELD_NUMBER;
    hash = (53 * hash) + getArg().hashCode();
    if (hasAnnotation()) {
      hash = (37 * hash) + ANNOTATION_FIELD_NUMBER;
      hash = (53 * hash) + getAnnotation().hashCode();
    }
    if (hasTypeComment()) {
      hash = (37 * hash) + TYPE_COMMENT_FIELD_NUMBER;
      hash = (53 * hash) + getTypeComment().hashCode();
    }
    hash = (37 * hash) + LINENO_FIELD_NUMBER;
    hash = (53 * hash) + getLineno();
    hash = (37 * hash) + COL_OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + getColOffset();
    if (hasEndLineno()) {
      hash = (37 * hash) + END_LINENO_FIELD_NUMBER;
      hash = (53 * hash) + getEndLineno();
    }
    if (hasEndColOffset()) {
      hash = (37 * hash) + END_COL_OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + getEndColOffset();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.giyeok.tython.proto.Arg parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.giyeok.tython.proto.Arg parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.giyeok.tython.proto.Arg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.giyeok.tython.proto.Arg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.giyeok.tython.proto.Arg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.giyeok.tython.proto.Arg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.giyeok.tython.proto.Arg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.giyeok.tython.proto.Arg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.giyeok.tython.proto.Arg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.giyeok.tython.proto.Arg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.giyeok.tython.proto.Arg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.giyeok.tython.proto.Arg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.giyeok.tython.proto.Arg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.giyeok.tython.proto.Arg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.giyeok.tython.proto.Arg)
      com.giyeok.tython.proto.ArgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_Arg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_Arg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.giyeok.tython.proto.Arg.class, com.giyeok.tython.proto.Arg.Builder.class);
    }

    // Construct using com.giyeok.tython.proto.Arg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAnnotationFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      arg_ = "";

      if (annotationBuilder_ == null) {
        annotation_ = null;
      } else {
        annotationBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      typeComment_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      lineno_ = 0;

      colOffset_ = 0;

      endLineno_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      endColOffset_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_Arg_descriptor;
    }

    @java.lang.Override
    public com.giyeok.tython.proto.Arg getDefaultInstanceForType() {
      return com.giyeok.tython.proto.Arg.getDefaultInstance();
    }

    @java.lang.Override
    public com.giyeok.tython.proto.Arg build() {
      com.giyeok.tython.proto.Arg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.giyeok.tython.proto.Arg buildPartial() {
      com.giyeok.tython.proto.Arg result = new com.giyeok.tython.proto.Arg(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.arg_ = arg_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (annotationBuilder_ == null) {
          result.annotation_ = annotation_;
        } else {
          result.annotation_ = annotationBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.typeComment_ = typeComment_;
      result.lineno_ = lineno_;
      result.colOffset_ = colOffset_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.endLineno_ = endLineno_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.endColOffset_ = endColOffset_;
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.giyeok.tython.proto.Arg) {
        return mergeFrom((com.giyeok.tython.proto.Arg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.giyeok.tython.proto.Arg other) {
      if (other == com.giyeok.tython.proto.Arg.getDefaultInstance()) return this;
      if (!other.getArg().isEmpty()) {
        arg_ = other.arg_;
        onChanged();
      }
      if (other.hasAnnotation()) {
        mergeAnnotation(other.getAnnotation());
      }
      if (other.hasTypeComment()) {
        bitField0_ |= 0x00000002;
        typeComment_ = other.typeComment_;
        onChanged();
      }
      if (other.getLineno() != 0) {
        setLineno(other.getLineno());
      }
      if (other.getColOffset() != 0) {
        setColOffset(other.getColOffset());
      }
      if (other.hasEndLineno()) {
        setEndLineno(other.getEndLineno());
      }
      if (other.hasEndColOffset()) {
        setEndColOffset(other.getEndColOffset());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.giyeok.tython.proto.Arg parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.giyeok.tython.proto.Arg) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object arg_ = "";
    /**
     * <code>string arg = 1;</code>
     * @return The arg.
     */
    public java.lang.String getArg() {
      java.lang.Object ref = arg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        arg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string arg = 1;</code>
     * @return The bytes for arg.
     */
    public com.google.protobuf.ByteString
        getArgBytes() {
      java.lang.Object ref = arg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        arg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string arg = 1;</code>
     * @param value The arg to set.
     * @return This builder for chaining.
     */
    public Builder setArg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      arg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string arg = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearArg() {
      
      arg_ = getDefaultInstance().getArg();
      onChanged();
      return this;
    }
    /**
     * <code>string arg = 1;</code>
     * @param value The bytes for arg to set.
     * @return This builder for chaining.
     */
    public Builder setArgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      arg_ = value;
      onChanged();
      return this;
    }

    private com.giyeok.tython.proto.AbstractExpr annotation_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder> annotationBuilder_;
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr annotation = 2;</code>
     * @return Whether the annotation field is set.
     */
    public boolean hasAnnotation() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr annotation = 2;</code>
     * @return The annotation.
     */
    public com.giyeok.tython.proto.AbstractExpr getAnnotation() {
      if (annotationBuilder_ == null) {
        return annotation_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : annotation_;
      } else {
        return annotationBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr annotation = 2;</code>
     */
    public Builder setAnnotation(com.giyeok.tython.proto.AbstractExpr value) {
      if (annotationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        annotation_ = value;
        onChanged();
      } else {
        annotationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr annotation = 2;</code>
     */
    public Builder setAnnotation(
        com.giyeok.tython.proto.AbstractExpr.Builder builderForValue) {
      if (annotationBuilder_ == null) {
        annotation_ = builderForValue.build();
        onChanged();
      } else {
        annotationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr annotation = 2;</code>
     */
    public Builder mergeAnnotation(com.giyeok.tython.proto.AbstractExpr value) {
      if (annotationBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            annotation_ != null &&
            annotation_ != com.giyeok.tython.proto.AbstractExpr.getDefaultInstance()) {
          annotation_ =
            com.giyeok.tython.proto.AbstractExpr.newBuilder(annotation_).mergeFrom(value).buildPartial();
        } else {
          annotation_ = value;
        }
        onChanged();
      } else {
        annotationBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr annotation = 2;</code>
     */
    public Builder clearAnnotation() {
      if (annotationBuilder_ == null) {
        annotation_ = null;
        onChanged();
      } else {
        annotationBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr annotation = 2;</code>
     */
    public com.giyeok.tython.proto.AbstractExpr.Builder getAnnotationBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getAnnotationFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr annotation = 2;</code>
     */
    public com.giyeok.tython.proto.AbstractExprOrBuilder getAnnotationOrBuilder() {
      if (annotationBuilder_ != null) {
        return annotationBuilder_.getMessageOrBuilder();
      } else {
        return annotation_ == null ?
            com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : annotation_;
      }
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr annotation = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder> 
        getAnnotationFieldBuilder() {
      if (annotationBuilder_ == null) {
        annotationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder>(
                getAnnotation(),
                getParentForChildren(),
                isClean());
        annotation_ = null;
      }
      return annotationBuilder_;
    }

    private java.lang.Object typeComment_ = "";
    /**
     * <code>optional string type_comment = 3;</code>
     * @return Whether the typeComment field is set.
     */
    public boolean hasTypeComment() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string type_comment = 3;</code>
     * @return The typeComment.
     */
    public java.lang.String getTypeComment() {
      java.lang.Object ref = typeComment_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        typeComment_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string type_comment = 3;</code>
     * @return The bytes for typeComment.
     */
    public com.google.protobuf.ByteString
        getTypeCommentBytes() {
      java.lang.Object ref = typeComment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typeComment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string type_comment = 3;</code>
     * @param value The typeComment to set.
     * @return This builder for chaining.
     */
    public Builder setTypeComment(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      typeComment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string type_comment = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTypeComment() {
      bitField0_ = (bitField0_ & ~0x00000002);
      typeComment_ = getDefaultInstance().getTypeComment();
      onChanged();
      return this;
    }
    /**
     * <code>optional string type_comment = 3;</code>
     * @param value The bytes for typeComment to set.
     * @return This builder for chaining.
     */
    public Builder setTypeCommentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      typeComment_ = value;
      onChanged();
      return this;
    }

    private int lineno_ ;
    /**
     * <code>int32 lineno = 4;</code>
     * @return The lineno.
     */
    @java.lang.Override
    public int getLineno() {
      return lineno_;
    }
    /**
     * <code>int32 lineno = 4;</code>
     * @param value The lineno to set.
     * @return This builder for chaining.
     */
    public Builder setLineno(int value) {
      
      lineno_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 lineno = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLineno() {
      
      lineno_ = 0;
      onChanged();
      return this;
    }

    private int colOffset_ ;
    /**
     * <code>int32 col_offset = 5;</code>
     * @return The colOffset.
     */
    @java.lang.Override
    public int getColOffset() {
      return colOffset_;
    }
    /**
     * <code>int32 col_offset = 5;</code>
     * @param value The colOffset to set.
     * @return This builder for chaining.
     */
    public Builder setColOffset(int value) {
      
      colOffset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 col_offset = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearColOffset() {
      
      colOffset_ = 0;
      onChanged();
      return this;
    }

    private int endLineno_ ;
    /**
     * <code>optional int32 end_lineno = 6;</code>
     * @return Whether the endLineno field is set.
     */
    @java.lang.Override
    public boolean hasEndLineno() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 end_lineno = 6;</code>
     * @return The endLineno.
     */
    @java.lang.Override
    public int getEndLineno() {
      return endLineno_;
    }
    /**
     * <code>optional int32 end_lineno = 6;</code>
     * @param value The endLineno to set.
     * @return This builder for chaining.
     */
    public Builder setEndLineno(int value) {
      bitField0_ |= 0x00000004;
      endLineno_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 end_lineno = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndLineno() {
      bitField0_ = (bitField0_ & ~0x00000004);
      endLineno_ = 0;
      onChanged();
      return this;
    }

    private int endColOffset_ ;
    /**
     * <code>optional int32 end_col_offset = 7;</code>
     * @return Whether the endColOffset field is set.
     */
    @java.lang.Override
    public boolean hasEndColOffset() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 end_col_offset = 7;</code>
     * @return The endColOffset.
     */
    @java.lang.Override
    public int getEndColOffset() {
      return endColOffset_;
    }
    /**
     * <code>optional int32 end_col_offset = 7;</code>
     * @param value The endColOffset to set.
     * @return This builder for chaining.
     */
    public Builder setEndColOffset(int value) {
      bitField0_ |= 0x00000008;
      endColOffset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 end_col_offset = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndColOffset() {
      bitField0_ = (bitField0_ & ~0x00000008);
      endColOffset_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.giyeok.tython.proto.Arg)
  }

  // @@protoc_insertion_point(class_scope:com.giyeok.tython.proto.Arg)
  private static final com.giyeok.tython.proto.Arg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.giyeok.tython.proto.Arg();
  }

  public static com.giyeok.tython.proto.Arg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Arg>
      PARSER = new com.google.protobuf.AbstractParser<Arg>() {
    @java.lang.Override
    public Arg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Arg(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Arg> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Arg> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.giyeok.tython.proto.Arg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

