// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: python3_10.proto

package com.giyeok.tython.proto;

public interface ArgumentsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.giyeok.tython.proto.Arguments)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.giyeok.tython.proto.Arg posonlyargs = 1;</code>
   */
  java.util.List<com.giyeok.tython.proto.Arg> 
      getPosonlyargsList();
  /**
   * <code>repeated .com.giyeok.tython.proto.Arg posonlyargs = 1;</code>
   */
  com.giyeok.tython.proto.Arg getPosonlyargs(int index);
  /**
   * <code>repeated .com.giyeok.tython.proto.Arg posonlyargs = 1;</code>
   */
  int getPosonlyargsCount();
  /**
   * <code>repeated .com.giyeok.tython.proto.Arg posonlyargs = 1;</code>
   */
  java.util.List<? extends com.giyeok.tython.proto.ArgOrBuilder> 
      getPosonlyargsOrBuilderList();
  /**
   * <code>repeated .com.giyeok.tython.proto.Arg posonlyargs = 1;</code>
   */
  com.giyeok.tython.proto.ArgOrBuilder getPosonlyargsOrBuilder(
      int index);

  /**
   * <code>repeated .com.giyeok.tython.proto.Arg args = 2;</code>
   */
  java.util.List<com.giyeok.tython.proto.Arg> 
      getArgsList();
  /**
   * <code>repeated .com.giyeok.tython.proto.Arg args = 2;</code>
   */
  com.giyeok.tython.proto.Arg getArgs(int index);
  /**
   * <code>repeated .com.giyeok.tython.proto.Arg args = 2;</code>
   */
  int getArgsCount();
  /**
   * <code>repeated .com.giyeok.tython.proto.Arg args = 2;</code>
   */
  java.util.List<? extends com.giyeok.tython.proto.ArgOrBuilder> 
      getArgsOrBuilderList();
  /**
   * <code>repeated .com.giyeok.tython.proto.Arg args = 2;</code>
   */
  com.giyeok.tython.proto.ArgOrBuilder getArgsOrBuilder(
      int index);

  /**
   * <code>optional .com.giyeok.tython.proto.Arg vararg = 3;</code>
   * @return Whether the vararg field is set.
   */
  boolean hasVararg();
  /**
   * <code>optional .com.giyeok.tython.proto.Arg vararg = 3;</code>
   * @return The vararg.
   */
  com.giyeok.tython.proto.Arg getVararg();
  /**
   * <code>optional .com.giyeok.tython.proto.Arg vararg = 3;</code>
   */
  com.giyeok.tython.proto.ArgOrBuilder getVarargOrBuilder();

  /**
   * <code>repeated .com.giyeok.tython.proto.Arg kwonlyargs = 4;</code>
   */
  java.util.List<com.giyeok.tython.proto.Arg> 
      getKwonlyargsList();
  /**
   * <code>repeated .com.giyeok.tython.proto.Arg kwonlyargs = 4;</code>
   */
  com.giyeok.tython.proto.Arg getKwonlyargs(int index);
  /**
   * <code>repeated .com.giyeok.tython.proto.Arg kwonlyargs = 4;</code>
   */
  int getKwonlyargsCount();
  /**
   * <code>repeated .com.giyeok.tython.proto.Arg kwonlyargs = 4;</code>
   */
  java.util.List<? extends com.giyeok.tython.proto.ArgOrBuilder> 
      getKwonlyargsOrBuilderList();
  /**
   * <code>repeated .com.giyeok.tython.proto.Arg kwonlyargs = 4;</code>
   */
  com.giyeok.tython.proto.ArgOrBuilder getKwonlyargsOrBuilder(
      int index);

  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr kw_defaults = 5;</code>
   */
  java.util.List<com.giyeok.tython.proto.AbstractExpr> 
      getKwDefaultsList();
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr kw_defaults = 5;</code>
   */
  com.giyeok.tython.proto.AbstractExpr getKwDefaults(int index);
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr kw_defaults = 5;</code>
   */
  int getKwDefaultsCount();
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr kw_defaults = 5;</code>
   */
  java.util.List<? extends com.giyeok.tython.proto.AbstractExprOrBuilder> 
      getKwDefaultsOrBuilderList();
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr kw_defaults = 5;</code>
   */
  com.giyeok.tython.proto.AbstractExprOrBuilder getKwDefaultsOrBuilder(
      int index);

  /**
   * <code>optional .com.giyeok.tython.proto.Arg kwarg = 6;</code>
   * @return Whether the kwarg field is set.
   */
  boolean hasKwarg();
  /**
   * <code>optional .com.giyeok.tython.proto.Arg kwarg = 6;</code>
   * @return The kwarg.
   */
  com.giyeok.tython.proto.Arg getKwarg();
  /**
   * <code>optional .com.giyeok.tython.proto.Arg kwarg = 6;</code>
   */
  com.giyeok.tython.proto.ArgOrBuilder getKwargOrBuilder();

  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr defaults = 7;</code>
   */
  java.util.List<com.giyeok.tython.proto.AbstractExpr> 
      getDefaultsList();
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr defaults = 7;</code>
   */
  com.giyeok.tython.proto.AbstractExpr getDefaults(int index);
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr defaults = 7;</code>
   */
  int getDefaultsCount();
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr defaults = 7;</code>
   */
  java.util.List<? extends com.giyeok.tython.proto.AbstractExprOrBuilder> 
      getDefaultsOrBuilderList();
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr defaults = 7;</code>
   */
  com.giyeok.tython.proto.AbstractExprOrBuilder getDefaultsOrBuilder(
      int index);
}
