// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: python3_10.proto

package com.giyeok.tython.proto;

public interface AttributeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.giyeok.tython.proto.Attribute)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.giyeok.tython.proto.AbstractExpr value = 1;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>.com.giyeok.tython.proto.AbstractExpr value = 1;</code>
   * @return The value.
   */
  com.giyeok.tython.proto.AbstractExpr getValue();
  /**
   * <code>.com.giyeok.tython.proto.AbstractExpr value = 1;</code>
   */
  com.giyeok.tython.proto.AbstractExprOrBuilder getValueOrBuilder();

  /**
   * <code>string attr = 2;</code>
   * @return The attr.
   */
  java.lang.String getAttr();
  /**
   * <code>string attr = 2;</code>
   * @return The bytes for attr.
   */
  com.google.protobuf.ByteString
      getAttrBytes();

  /**
   * <code>.com.giyeok.tython.proto.AbstractExprContext ctx = 3;</code>
   * @return Whether the ctx field is set.
   */
  boolean hasCtx();
  /**
   * <code>.com.giyeok.tython.proto.AbstractExprContext ctx = 3;</code>
   * @return The ctx.
   */
  com.giyeok.tython.proto.AbstractExprContext getCtx();
  /**
   * <code>.com.giyeok.tython.proto.AbstractExprContext ctx = 3;</code>
   */
  com.giyeok.tython.proto.AbstractExprContextOrBuilder getCtxOrBuilder();

  /**
   * <code>int32 lineno = 4;</code>
   * @return The lineno.
   */
  int getLineno();

  /**
   * <code>int32 col_offset = 5;</code>
   * @return The colOffset.
   */
  int getColOffset();

  /**
   * <code>optional int32 end_lineno = 6;</code>
   * @return Whether the endLineno field is set.
   */
  boolean hasEndLineno();
  /**
   * <code>optional int32 end_lineno = 6;</code>
   * @return The endLineno.
   */
  int getEndLineno();

  /**
   * <code>optional int32 end_col_offset = 7;</code>
   * @return Whether the endColOffset field is set.
   */
  boolean hasEndColOffset();
  /**
   * <code>optional int32 end_col_offset = 7;</code>
   * @return The endColOffset.
   */
  int getEndColOffset();
}
