// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: python3_10.proto

package com.giyeok.tython.proto;

public interface BitOrOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.giyeok.tython.proto.BitOr)
    com.google.protobuf.MessageOrBuilder {
}
