// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: python3_10.proto

package com.giyeok.tython.proto;

/**
 * Protobuf type {@code com.giyeok.tython.proto.FormattedValue}
 */
public final class FormattedValue extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.giyeok.tython.proto.FormattedValue)
    FormattedValueOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FormattedValue.newBuilder() to construct.
  private FormattedValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FormattedValue() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FormattedValue();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FormattedValue(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.giyeok.tython.proto.AbstractExpr.Builder subBuilder = null;
            if (value_ != null) {
              subBuilder = value_.toBuilder();
            }
            value_ = input.readMessage(com.giyeok.tython.proto.AbstractExpr.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(value_);
              value_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            conversion_ = input.readInt32();
            break;
          }
          case 26: {
            com.giyeok.tython.proto.AbstractExpr.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = formatSpec_.toBuilder();
            }
            formatSpec_ = input.readMessage(com.giyeok.tython.proto.AbstractExpr.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(formatSpec_);
              formatSpec_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 32: {

            lineno_ = input.readInt32();
            break;
          }
          case 40: {

            colOffset_ = input.readInt32();
            break;
          }
          case 48: {
            bitField0_ |= 0x00000002;
            endLineno_ = input.readInt32();
            break;
          }
          case 56: {
            bitField0_ |= 0x00000004;
            endColOffset_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_FormattedValue_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_FormattedValue_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.giyeok.tython.proto.FormattedValue.class, com.giyeok.tython.proto.FormattedValue.Builder.class);
  }

  private int bitField0_;
  public static final int VALUE_FIELD_NUMBER = 1;
  private com.giyeok.tython.proto.AbstractExpr value_;
  /**
   * <code>.com.giyeok.tython.proto.AbstractExpr value = 1;</code>
   * @return Whether the value field is set.
   */
  @java.lang.Override
  public boolean hasValue() {
    return value_ != null;
  }
  /**
   * <code>.com.giyeok.tython.proto.AbstractExpr value = 1;</code>
   * @return The value.
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractExpr getValue() {
    return value_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : value_;
  }
  /**
   * <code>.com.giyeok.tython.proto.AbstractExpr value = 1;</code>
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractExprOrBuilder getValueOrBuilder() {
    return getValue();
  }

  public static final int CONVERSION_FIELD_NUMBER = 2;
  private int conversion_;
  /**
   * <code>int32 conversion = 2;</code>
   * @return The conversion.
   */
  @java.lang.Override
  public int getConversion() {
    return conversion_;
  }

  public static final int FORMAT_SPEC_FIELD_NUMBER = 3;
  private com.giyeok.tython.proto.AbstractExpr formatSpec_;
  /**
   * <code>optional .com.giyeok.tython.proto.AbstractExpr format_spec = 3;</code>
   * @return Whether the formatSpec field is set.
   */
  @java.lang.Override
  public boolean hasFormatSpec() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .com.giyeok.tython.proto.AbstractExpr format_spec = 3;</code>
   * @return The formatSpec.
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractExpr getFormatSpec() {
    return formatSpec_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : formatSpec_;
  }
  /**
   * <code>optional .com.giyeok.tython.proto.AbstractExpr format_spec = 3;</code>
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractExprOrBuilder getFormatSpecOrBuilder() {
    return formatSpec_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : formatSpec_;
  }

  public static final int LINENO_FIELD_NUMBER = 4;
  private int lineno_;
  /**
   * <code>int32 lineno = 4;</code>
   * @return The lineno.
   */
  @java.lang.Override
  public int getLineno() {
    return lineno_;
  }

  public static final int COL_OFFSET_FIELD_NUMBER = 5;
  private int colOffset_;
  /**
   * <code>int32 col_offset = 5;</code>
   * @return The colOffset.
   */
  @java.lang.Override
  public int getColOffset() {
    return colOffset_;
  }

  public static final int END_LINENO_FIELD_NUMBER = 6;
  private int endLineno_;
  /**
   * <code>optional int32 end_lineno = 6;</code>
   * @return Whether the endLineno field is set.
   */
  @java.lang.Override
  public boolean hasEndLineno() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int32 end_lineno = 6;</code>
   * @return The endLineno.
   */
  @java.lang.Override
  public int getEndLineno() {
    return endLineno_;
  }

  public static final int END_COL_OFFSET_FIELD_NUMBER = 7;
  private int endColOffset_;
  /**
   * <code>optional int32 end_col_offset = 7;</code>
   * @return Whether the endColOffset field is set.
   */
  @java.lang.Override
  public boolean hasEndColOffset() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int32 end_col_offset = 7;</code>
   * @return The endColOffset.
   */
  @java.lang.Override
  public int getEndColOffset() {
    return endColOffset_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (value_ != null) {
      output.writeMessage(1, getValue());
    }
    if (conversion_ != 0) {
      output.writeInt32(2, conversion_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getFormatSpec());
    }
    if (lineno_ != 0) {
      output.writeInt32(4, lineno_);
    }
    if (colOffset_ != 0) {
      output.writeInt32(5, colOffset_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(6, endLineno_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(7, endColOffset_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (value_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getValue());
    }
    if (conversion_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, conversion_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getFormatSpec());
    }
    if (lineno_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, lineno_);
    }
    if (colOffset_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, colOffset_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, endLineno_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, endColOffset_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.giyeok.tython.proto.FormattedValue)) {
      return super.equals(obj);
    }
    com.giyeok.tython.proto.FormattedValue other = (com.giyeok.tython.proto.FormattedValue) obj;

    if (hasValue() != other.hasValue()) return false;
    if (hasValue()) {
      if (!getValue()
          .equals(other.getValue())) return false;
    }
    if (getConversion()
        != other.getConversion()) return false;
    if (hasFormatSpec() != other.hasFormatSpec()) return false;
    if (hasFormatSpec()) {
      if (!getFormatSpec()
          .equals(other.getFormatSpec())) return false;
    }
    if (getLineno()
        != other.getLineno()) return false;
    if (getColOffset()
        != other.getColOffset()) return false;
    if (hasEndLineno() != other.hasEndLineno()) return false;
    if (hasEndLineno()) {
      if (getEndLineno()
          != other.getEndLineno()) return false;
    }
    if (hasEndColOffset() != other.hasEndColOffset()) return false;
    if (hasEndColOffset()) {
      if (getEndColOffset()
          != other.getEndColOffset()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasValue()) {
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
    }
    hash = (37 * hash) + CONVERSION_FIELD_NUMBER;
    hash = (53 * hash) + getConversion();
    if (hasFormatSpec()) {
      hash = (37 * hash) + FORMAT_SPEC_FIELD_NUMBER;
      hash = (53 * hash) + getFormatSpec().hashCode();
    }
    hash = (37 * hash) + LINENO_FIELD_NUMBER;
    hash = (53 * hash) + getLineno();
    hash = (37 * hash) + COL_OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + getColOffset();
    if (hasEndLineno()) {
      hash = (37 * hash) + END_LINENO_FIELD_NUMBER;
      hash = (53 * hash) + getEndLineno();
    }
    if (hasEndColOffset()) {
      hash = (37 * hash) + END_COL_OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + getEndColOffset();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.giyeok.tython.proto.FormattedValue parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.giyeok.tython.proto.FormattedValue parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.giyeok.tython.proto.FormattedValue parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.giyeok.tython.proto.FormattedValue parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.giyeok.tython.proto.FormattedValue parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.giyeok.tython.proto.FormattedValue parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.giyeok.tython.proto.FormattedValue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.giyeok.tython.proto.FormattedValue parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.giyeok.tython.proto.FormattedValue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.giyeok.tython.proto.FormattedValue parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.giyeok.tython.proto.FormattedValue parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.giyeok.tython.proto.FormattedValue parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.giyeok.tython.proto.FormattedValue prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.giyeok.tython.proto.FormattedValue}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.giyeok.tython.proto.FormattedValue)
      com.giyeok.tython.proto.FormattedValueOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_FormattedValue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_FormattedValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.giyeok.tython.proto.FormattedValue.class, com.giyeok.tython.proto.FormattedValue.Builder.class);
    }

    // Construct using com.giyeok.tython.proto.FormattedValue.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFormatSpecFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (valueBuilder_ == null) {
        value_ = null;
      } else {
        value_ = null;
        valueBuilder_ = null;
      }
      conversion_ = 0;

      if (formatSpecBuilder_ == null) {
        formatSpec_ = null;
      } else {
        formatSpecBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      lineno_ = 0;

      colOffset_ = 0;

      endLineno_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      endColOffset_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_FormattedValue_descriptor;
    }

    @java.lang.Override
    public com.giyeok.tython.proto.FormattedValue getDefaultInstanceForType() {
      return com.giyeok.tython.proto.FormattedValue.getDefaultInstance();
    }

    @java.lang.Override
    public com.giyeok.tython.proto.FormattedValue build() {
      com.giyeok.tython.proto.FormattedValue result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.giyeok.tython.proto.FormattedValue buildPartial() {
      com.giyeok.tython.proto.FormattedValue result = new com.giyeok.tython.proto.FormattedValue(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (valueBuilder_ == null) {
        result.value_ = value_;
      } else {
        result.value_ = valueBuilder_.build();
      }
      result.conversion_ = conversion_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (formatSpecBuilder_ == null) {
          result.formatSpec_ = formatSpec_;
        } else {
          result.formatSpec_ = formatSpecBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      result.lineno_ = lineno_;
      result.colOffset_ = colOffset_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.endLineno_ = endLineno_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.endColOffset_ = endColOffset_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.giyeok.tython.proto.FormattedValue) {
        return mergeFrom((com.giyeok.tython.proto.FormattedValue)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.giyeok.tython.proto.FormattedValue other) {
      if (other == com.giyeok.tython.proto.FormattedValue.getDefaultInstance()) return this;
      if (other.hasValue()) {
        mergeValue(other.getValue());
      }
      if (other.getConversion() != 0) {
        setConversion(other.getConversion());
      }
      if (other.hasFormatSpec()) {
        mergeFormatSpec(other.getFormatSpec());
      }
      if (other.getLineno() != 0) {
        setLineno(other.getLineno());
      }
      if (other.getColOffset() != 0) {
        setColOffset(other.getColOffset());
      }
      if (other.hasEndLineno()) {
        setEndLineno(other.getEndLineno());
      }
      if (other.hasEndColOffset()) {
        setEndColOffset(other.getEndColOffset());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.giyeok.tython.proto.FormattedValue parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.giyeok.tython.proto.FormattedValue) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.giyeok.tython.proto.AbstractExpr value_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder> valueBuilder_;
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr value = 1;</code>
     * @return Whether the value field is set.
     */
    public boolean hasValue() {
      return valueBuilder_ != null || value_ != null;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr value = 1;</code>
     * @return The value.
     */
    public com.giyeok.tython.proto.AbstractExpr getValue() {
      if (valueBuilder_ == null) {
        return value_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : value_;
      } else {
        return valueBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr value = 1;</code>
     */
    public Builder setValue(com.giyeok.tython.proto.AbstractExpr value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
        onChanged();
      } else {
        valueBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr value = 1;</code>
     */
    public Builder setValue(
        com.giyeok.tython.proto.AbstractExpr.Builder builderForValue) {
      if (valueBuilder_ == null) {
        value_ = builderForValue.build();
        onChanged();
      } else {
        valueBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr value = 1;</code>
     */
    public Builder mergeValue(com.giyeok.tython.proto.AbstractExpr value) {
      if (valueBuilder_ == null) {
        if (value_ != null) {
          value_ =
            com.giyeok.tython.proto.AbstractExpr.newBuilder(value_).mergeFrom(value).buildPartial();
        } else {
          value_ = value;
        }
        onChanged();
      } else {
        valueBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr value = 1;</code>
     */
    public Builder clearValue() {
      if (valueBuilder_ == null) {
        value_ = null;
        onChanged();
      } else {
        value_ = null;
        valueBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr value = 1;</code>
     */
    public com.giyeok.tython.proto.AbstractExpr.Builder getValueBuilder() {
      
      onChanged();
      return getValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr value = 1;</code>
     */
    public com.giyeok.tython.proto.AbstractExprOrBuilder getValueOrBuilder() {
      if (valueBuilder_ != null) {
        return valueBuilder_.getMessageOrBuilder();
      } else {
        return value_ == null ?
            com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : value_;
      }
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr value = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder> 
        getValueFieldBuilder() {
      if (valueBuilder_ == null) {
        valueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder>(
                getValue(),
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      return valueBuilder_;
    }

    private int conversion_ ;
    /**
     * <code>int32 conversion = 2;</code>
     * @return The conversion.
     */
    @java.lang.Override
    public int getConversion() {
      return conversion_;
    }
    /**
     * <code>int32 conversion = 2;</code>
     * @param value The conversion to set.
     * @return This builder for chaining.
     */
    public Builder setConversion(int value) {
      
      conversion_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 conversion = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearConversion() {
      
      conversion_ = 0;
      onChanged();
      return this;
    }

    private com.giyeok.tython.proto.AbstractExpr formatSpec_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder> formatSpecBuilder_;
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr format_spec = 3;</code>
     * @return Whether the formatSpec field is set.
     */
    public boolean hasFormatSpec() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr format_spec = 3;</code>
     * @return The formatSpec.
     */
    public com.giyeok.tython.proto.AbstractExpr getFormatSpec() {
      if (formatSpecBuilder_ == null) {
        return formatSpec_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : formatSpec_;
      } else {
        return formatSpecBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr format_spec = 3;</code>
     */
    public Builder setFormatSpec(com.giyeok.tython.proto.AbstractExpr value) {
      if (formatSpecBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        formatSpec_ = value;
        onChanged();
      } else {
        formatSpecBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr format_spec = 3;</code>
     */
    public Builder setFormatSpec(
        com.giyeok.tython.proto.AbstractExpr.Builder builderForValue) {
      if (formatSpecBuilder_ == null) {
        formatSpec_ = builderForValue.build();
        onChanged();
      } else {
        formatSpecBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr format_spec = 3;</code>
     */
    public Builder mergeFormatSpec(com.giyeok.tython.proto.AbstractExpr value) {
      if (formatSpecBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            formatSpec_ != null &&
            formatSpec_ != com.giyeok.tython.proto.AbstractExpr.getDefaultInstance()) {
          formatSpec_ =
            com.giyeok.tython.proto.AbstractExpr.newBuilder(formatSpec_).mergeFrom(value).buildPartial();
        } else {
          formatSpec_ = value;
        }
        onChanged();
      } else {
        formatSpecBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr format_spec = 3;</code>
     */
    public Builder clearFormatSpec() {
      if (formatSpecBuilder_ == null) {
        formatSpec_ = null;
        onChanged();
      } else {
        formatSpecBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr format_spec = 3;</code>
     */
    public com.giyeok.tython.proto.AbstractExpr.Builder getFormatSpecBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getFormatSpecFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr format_spec = 3;</code>
     */
    public com.giyeok.tython.proto.AbstractExprOrBuilder getFormatSpecOrBuilder() {
      if (formatSpecBuilder_ != null) {
        return formatSpecBuilder_.getMessageOrBuilder();
      } else {
        return formatSpec_ == null ?
            com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : formatSpec_;
      }
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr format_spec = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder> 
        getFormatSpecFieldBuilder() {
      if (formatSpecBuilder_ == null) {
        formatSpecBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder>(
                getFormatSpec(),
                getParentForChildren(),
                isClean());
        formatSpec_ = null;
      }
      return formatSpecBuilder_;
    }

    private int lineno_ ;
    /**
     * <code>int32 lineno = 4;</code>
     * @return The lineno.
     */
    @java.lang.Override
    public int getLineno() {
      return lineno_;
    }
    /**
     * <code>int32 lineno = 4;</code>
     * @param value The lineno to set.
     * @return This builder for chaining.
     */
    public Builder setLineno(int value) {
      
      lineno_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 lineno = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLineno() {
      
      lineno_ = 0;
      onChanged();
      return this;
    }

    private int colOffset_ ;
    /**
     * <code>int32 col_offset = 5;</code>
     * @return The colOffset.
     */
    @java.lang.Override
    public int getColOffset() {
      return colOffset_;
    }
    /**
     * <code>int32 col_offset = 5;</code>
     * @param value The colOffset to set.
     * @return This builder for chaining.
     */
    public Builder setColOffset(int value) {
      
      colOffset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 col_offset = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearColOffset() {
      
      colOffset_ = 0;
      onChanged();
      return this;
    }

    private int endLineno_ ;
    /**
     * <code>optional int32 end_lineno = 6;</code>
     * @return Whether the endLineno field is set.
     */
    @java.lang.Override
    public boolean hasEndLineno() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 end_lineno = 6;</code>
     * @return The endLineno.
     */
    @java.lang.Override
    public int getEndLineno() {
      return endLineno_;
    }
    /**
     * <code>optional int32 end_lineno = 6;</code>
     * @param value The endLineno to set.
     * @return This builder for chaining.
     */
    public Builder setEndLineno(int value) {
      bitField0_ |= 0x00000002;
      endLineno_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 end_lineno = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndLineno() {
      bitField0_ = (bitField0_ & ~0x00000002);
      endLineno_ = 0;
      onChanged();
      return this;
    }

    private int endColOffset_ ;
    /**
     * <code>optional int32 end_col_offset = 7;</code>
     * @return Whether the endColOffset field is set.
     */
    @java.lang.Override
    public boolean hasEndColOffset() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 end_col_offset = 7;</code>
     * @return The endColOffset.
     */
    @java.lang.Override
    public int getEndColOffset() {
      return endColOffset_;
    }
    /**
     * <code>optional int32 end_col_offset = 7;</code>
     * @param value The endColOffset to set.
     * @return This builder for chaining.
     */
    public Builder setEndColOffset(int value) {
      bitField0_ |= 0x00000004;
      endColOffset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 end_col_offset = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndColOffset() {
      bitField0_ = (bitField0_ & ~0x00000004);
      endColOffset_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.giyeok.tython.proto.FormattedValue)
  }

  // @@protoc_insertion_point(class_scope:com.giyeok.tython.proto.FormattedValue)
  private static final com.giyeok.tython.proto.FormattedValue DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.giyeok.tython.proto.FormattedValue();
  }

  public static com.giyeok.tython.proto.FormattedValue getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FormattedValue>
      PARSER = new com.google.protobuf.AbstractParser<FormattedValue>() {
    @java.lang.Override
    public FormattedValue parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FormattedValue(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FormattedValue> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FormattedValue> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.giyeok.tython.proto.FormattedValue getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

