// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: python3_10.proto

package com.giyeok.tython.proto;

/**
 * Protobuf type {@code com.giyeok.tython.proto.FunctionType}
 */
public final class FunctionType extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.giyeok.tython.proto.FunctionType)
    FunctionTypeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FunctionType.newBuilder() to construct.
  private FunctionType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FunctionType() {
    argtypes_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FunctionType();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FunctionType(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              argtypes_ = new java.util.ArrayList<com.giyeok.tython.proto.AbstractExpr>();
              mutable_bitField0_ |= 0x00000001;
            }
            argtypes_.add(
                input.readMessage(com.giyeok.tython.proto.AbstractExpr.parser(), extensionRegistry));
            break;
          }
          case 18: {
            com.giyeok.tython.proto.AbstractExpr.Builder subBuilder = null;
            if (returns_ != null) {
              subBuilder = returns_.toBuilder();
            }
            returns_ = input.readMessage(com.giyeok.tython.proto.AbstractExpr.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(returns_);
              returns_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        argtypes_ = java.util.Collections.unmodifiableList(argtypes_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_FunctionType_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_FunctionType_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.giyeok.tython.proto.FunctionType.class, com.giyeok.tython.proto.FunctionType.Builder.class);
  }

  public static final int ARGTYPES_FIELD_NUMBER = 1;
  private java.util.List<com.giyeok.tython.proto.AbstractExpr> argtypes_;
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.giyeok.tython.proto.AbstractExpr> getArgtypesList() {
    return argtypes_;
  }
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.giyeok.tython.proto.AbstractExprOrBuilder> 
      getArgtypesOrBuilderList() {
    return argtypes_;
  }
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
   */
  @java.lang.Override
  public int getArgtypesCount() {
    return argtypes_.size();
  }
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractExpr getArgtypes(int index) {
    return argtypes_.get(index);
  }
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractExprOrBuilder getArgtypesOrBuilder(
      int index) {
    return argtypes_.get(index);
  }

  public static final int RETURNS_FIELD_NUMBER = 2;
  private com.giyeok.tython.proto.AbstractExpr returns_;
  /**
   * <code>.com.giyeok.tython.proto.AbstractExpr returns = 2;</code>
   * @return Whether the returns field is set.
   */
  @java.lang.Override
  public boolean hasReturns() {
    return returns_ != null;
  }
  /**
   * <code>.com.giyeok.tython.proto.AbstractExpr returns = 2;</code>
   * @return The returns.
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractExpr getReturns() {
    return returns_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : returns_;
  }
  /**
   * <code>.com.giyeok.tython.proto.AbstractExpr returns = 2;</code>
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractExprOrBuilder getReturnsOrBuilder() {
    return getReturns();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < argtypes_.size(); i++) {
      output.writeMessage(1, argtypes_.get(i));
    }
    if (returns_ != null) {
      output.writeMessage(2, getReturns());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < argtypes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, argtypes_.get(i));
    }
    if (returns_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getReturns());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.giyeok.tython.proto.FunctionType)) {
      return super.equals(obj);
    }
    com.giyeok.tython.proto.FunctionType other = (com.giyeok.tython.proto.FunctionType) obj;

    if (!getArgtypesList()
        .equals(other.getArgtypesList())) return false;
    if (hasReturns() != other.hasReturns()) return false;
    if (hasReturns()) {
      if (!getReturns()
          .equals(other.getReturns())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getArgtypesCount() > 0) {
      hash = (37 * hash) + ARGTYPES_FIELD_NUMBER;
      hash = (53 * hash) + getArgtypesList().hashCode();
    }
    if (hasReturns()) {
      hash = (37 * hash) + RETURNS_FIELD_NUMBER;
      hash = (53 * hash) + getReturns().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.giyeok.tython.proto.FunctionType parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.giyeok.tython.proto.FunctionType parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.giyeok.tython.proto.FunctionType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.giyeok.tython.proto.FunctionType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.giyeok.tython.proto.FunctionType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.giyeok.tython.proto.FunctionType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.giyeok.tython.proto.FunctionType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.giyeok.tython.proto.FunctionType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.giyeok.tython.proto.FunctionType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.giyeok.tython.proto.FunctionType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.giyeok.tython.proto.FunctionType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.giyeok.tython.proto.FunctionType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.giyeok.tython.proto.FunctionType prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.giyeok.tython.proto.FunctionType}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.giyeok.tython.proto.FunctionType)
      com.giyeok.tython.proto.FunctionTypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_FunctionType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_FunctionType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.giyeok.tython.proto.FunctionType.class, com.giyeok.tython.proto.FunctionType.Builder.class);
    }

    // Construct using com.giyeok.tython.proto.FunctionType.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getArgtypesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (argtypesBuilder_ == null) {
        argtypes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        argtypesBuilder_.clear();
      }
      if (returnsBuilder_ == null) {
        returns_ = null;
      } else {
        returns_ = null;
        returnsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_FunctionType_descriptor;
    }

    @java.lang.Override
    public com.giyeok.tython.proto.FunctionType getDefaultInstanceForType() {
      return com.giyeok.tython.proto.FunctionType.getDefaultInstance();
    }

    @java.lang.Override
    public com.giyeok.tython.proto.FunctionType build() {
      com.giyeok.tython.proto.FunctionType result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.giyeok.tython.proto.FunctionType buildPartial() {
      com.giyeok.tython.proto.FunctionType result = new com.giyeok.tython.proto.FunctionType(this);
      int from_bitField0_ = bitField0_;
      if (argtypesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          argtypes_ = java.util.Collections.unmodifiableList(argtypes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.argtypes_ = argtypes_;
      } else {
        result.argtypes_ = argtypesBuilder_.build();
      }
      if (returnsBuilder_ == null) {
        result.returns_ = returns_;
      } else {
        result.returns_ = returnsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.giyeok.tython.proto.FunctionType) {
        return mergeFrom((com.giyeok.tython.proto.FunctionType)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.giyeok.tython.proto.FunctionType other) {
      if (other == com.giyeok.tython.proto.FunctionType.getDefaultInstance()) return this;
      if (argtypesBuilder_ == null) {
        if (!other.argtypes_.isEmpty()) {
          if (argtypes_.isEmpty()) {
            argtypes_ = other.argtypes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureArgtypesIsMutable();
            argtypes_.addAll(other.argtypes_);
          }
          onChanged();
        }
      } else {
        if (!other.argtypes_.isEmpty()) {
          if (argtypesBuilder_.isEmpty()) {
            argtypesBuilder_.dispose();
            argtypesBuilder_ = null;
            argtypes_ = other.argtypes_;
            bitField0_ = (bitField0_ & ~0x00000001);
            argtypesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getArgtypesFieldBuilder() : null;
          } else {
            argtypesBuilder_.addAllMessages(other.argtypes_);
          }
        }
      }
      if (other.hasReturns()) {
        mergeReturns(other.getReturns());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.giyeok.tython.proto.FunctionType parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.giyeok.tython.proto.FunctionType) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.giyeok.tython.proto.AbstractExpr> argtypes_ =
      java.util.Collections.emptyList();
    private void ensureArgtypesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        argtypes_ = new java.util.ArrayList<com.giyeok.tython.proto.AbstractExpr>(argtypes_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder> argtypesBuilder_;

    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
     */
    public java.util.List<com.giyeok.tython.proto.AbstractExpr> getArgtypesList() {
      if (argtypesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(argtypes_);
      } else {
        return argtypesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
     */
    public int getArgtypesCount() {
      if (argtypesBuilder_ == null) {
        return argtypes_.size();
      } else {
        return argtypesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
     */
    public com.giyeok.tython.proto.AbstractExpr getArgtypes(int index) {
      if (argtypesBuilder_ == null) {
        return argtypes_.get(index);
      } else {
        return argtypesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
     */
    public Builder setArgtypes(
        int index, com.giyeok.tython.proto.AbstractExpr value) {
      if (argtypesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArgtypesIsMutable();
        argtypes_.set(index, value);
        onChanged();
      } else {
        argtypesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
     */
    public Builder setArgtypes(
        int index, com.giyeok.tython.proto.AbstractExpr.Builder builderForValue) {
      if (argtypesBuilder_ == null) {
        ensureArgtypesIsMutable();
        argtypes_.set(index, builderForValue.build());
        onChanged();
      } else {
        argtypesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
     */
    public Builder addArgtypes(com.giyeok.tython.proto.AbstractExpr value) {
      if (argtypesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArgtypesIsMutable();
        argtypes_.add(value);
        onChanged();
      } else {
        argtypesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
     */
    public Builder addArgtypes(
        int index, com.giyeok.tython.proto.AbstractExpr value) {
      if (argtypesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArgtypesIsMutable();
        argtypes_.add(index, value);
        onChanged();
      } else {
        argtypesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
     */
    public Builder addArgtypes(
        com.giyeok.tython.proto.AbstractExpr.Builder builderForValue) {
      if (argtypesBuilder_ == null) {
        ensureArgtypesIsMutable();
        argtypes_.add(builderForValue.build());
        onChanged();
      } else {
        argtypesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
     */
    public Builder addArgtypes(
        int index, com.giyeok.tython.proto.AbstractExpr.Builder builderForValue) {
      if (argtypesBuilder_ == null) {
        ensureArgtypesIsMutable();
        argtypes_.add(index, builderForValue.build());
        onChanged();
      } else {
        argtypesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
     */
    public Builder addAllArgtypes(
        java.lang.Iterable<? extends com.giyeok.tython.proto.AbstractExpr> values) {
      if (argtypesBuilder_ == null) {
        ensureArgtypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, argtypes_);
        onChanged();
      } else {
        argtypesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
     */
    public Builder clearArgtypes() {
      if (argtypesBuilder_ == null) {
        argtypes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        argtypesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
     */
    public Builder removeArgtypes(int index) {
      if (argtypesBuilder_ == null) {
        ensureArgtypesIsMutable();
        argtypes_.remove(index);
        onChanged();
      } else {
        argtypesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
     */
    public com.giyeok.tython.proto.AbstractExpr.Builder getArgtypesBuilder(
        int index) {
      return getArgtypesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
     */
    public com.giyeok.tython.proto.AbstractExprOrBuilder getArgtypesOrBuilder(
        int index) {
      if (argtypesBuilder_ == null) {
        return argtypes_.get(index);  } else {
        return argtypesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
     */
    public java.util.List<? extends com.giyeok.tython.proto.AbstractExprOrBuilder> 
         getArgtypesOrBuilderList() {
      if (argtypesBuilder_ != null) {
        return argtypesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(argtypes_);
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
     */
    public com.giyeok.tython.proto.AbstractExpr.Builder addArgtypesBuilder() {
      return getArgtypesFieldBuilder().addBuilder(
          com.giyeok.tython.proto.AbstractExpr.getDefaultInstance());
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
     */
    public com.giyeok.tython.proto.AbstractExpr.Builder addArgtypesBuilder(
        int index) {
      return getArgtypesFieldBuilder().addBuilder(
          index, com.giyeok.tython.proto.AbstractExpr.getDefaultInstance());
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
     */
    public java.util.List<com.giyeok.tython.proto.AbstractExpr.Builder> 
         getArgtypesBuilderList() {
      return getArgtypesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder> 
        getArgtypesFieldBuilder() {
      if (argtypesBuilder_ == null) {
        argtypesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder>(
                argtypes_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        argtypes_ = null;
      }
      return argtypesBuilder_;
    }

    private com.giyeok.tython.proto.AbstractExpr returns_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder> returnsBuilder_;
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr returns = 2;</code>
     * @return Whether the returns field is set.
     */
    public boolean hasReturns() {
      return returnsBuilder_ != null || returns_ != null;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr returns = 2;</code>
     * @return The returns.
     */
    public com.giyeok.tython.proto.AbstractExpr getReturns() {
      if (returnsBuilder_ == null) {
        return returns_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : returns_;
      } else {
        return returnsBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr returns = 2;</code>
     */
    public Builder setReturns(com.giyeok.tython.proto.AbstractExpr value) {
      if (returnsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        returns_ = value;
        onChanged();
      } else {
        returnsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr returns = 2;</code>
     */
    public Builder setReturns(
        com.giyeok.tython.proto.AbstractExpr.Builder builderForValue) {
      if (returnsBuilder_ == null) {
        returns_ = builderForValue.build();
        onChanged();
      } else {
        returnsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr returns = 2;</code>
     */
    public Builder mergeReturns(com.giyeok.tython.proto.AbstractExpr value) {
      if (returnsBuilder_ == null) {
        if (returns_ != null) {
          returns_ =
            com.giyeok.tython.proto.AbstractExpr.newBuilder(returns_).mergeFrom(value).buildPartial();
        } else {
          returns_ = value;
        }
        onChanged();
      } else {
        returnsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr returns = 2;</code>
     */
    public Builder clearReturns() {
      if (returnsBuilder_ == null) {
        returns_ = null;
        onChanged();
      } else {
        returns_ = null;
        returnsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr returns = 2;</code>
     */
    public com.giyeok.tython.proto.AbstractExpr.Builder getReturnsBuilder() {
      
      onChanged();
      return getReturnsFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr returns = 2;</code>
     */
    public com.giyeok.tython.proto.AbstractExprOrBuilder getReturnsOrBuilder() {
      if (returnsBuilder_ != null) {
        return returnsBuilder_.getMessageOrBuilder();
      } else {
        return returns_ == null ?
            com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : returns_;
      }
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr returns = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder> 
        getReturnsFieldBuilder() {
      if (returnsBuilder_ == null) {
        returnsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder>(
                getReturns(),
                getParentForChildren(),
                isClean());
        returns_ = null;
      }
      return returnsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.giyeok.tython.proto.FunctionType)
  }

  // @@protoc_insertion_point(class_scope:com.giyeok.tython.proto.FunctionType)
  private static final com.giyeok.tython.proto.FunctionType DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.giyeok.tython.proto.FunctionType();
  }

  public static com.giyeok.tython.proto.FunctionType getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FunctionType>
      PARSER = new com.google.protobuf.AbstractParser<FunctionType>() {
    @java.lang.Override
    public FunctionType parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FunctionType(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FunctionType> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FunctionType> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.giyeok.tython.proto.FunctionType getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

