// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: python3_10.proto

package com.giyeok.tython.proto;

public interface FunctionTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.giyeok.tython.proto.FunctionType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
   */
  java.util.List<com.giyeok.tython.proto.AbstractExpr> 
      getArgtypesList();
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
   */
  com.giyeok.tython.proto.AbstractExpr getArgtypes(int index);
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
   */
  int getArgtypesCount();
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
   */
  java.util.List<? extends com.giyeok.tython.proto.AbstractExprOrBuilder> 
      getArgtypesOrBuilderList();
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr argtypes = 1;</code>
   */
  com.giyeok.tython.proto.AbstractExprOrBuilder getArgtypesOrBuilder(
      int index);

  /**
   * <code>.com.giyeok.tython.proto.AbstractExpr returns = 2;</code>
   * @return Whether the returns field is set.
   */
  boolean hasReturns();
  /**
   * <code>.com.giyeok.tython.proto.AbstractExpr returns = 2;</code>
   * @return The returns.
   */
  com.giyeok.tython.proto.AbstractExpr getReturns();
  /**
   * <code>.com.giyeok.tython.proto.AbstractExpr returns = 2;</code>
   */
  com.giyeok.tython.proto.AbstractExprOrBuilder getReturnsOrBuilder();
}
