// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: python3_10.proto

package com.giyeok.tython.proto;

public interface ImportFromOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.giyeok.tython.proto.ImportFrom)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string module = 1;</code>
   * @return Whether the module field is set.
   */
  boolean hasModule();
  /**
   * <code>optional string module = 1;</code>
   * @return The module.
   */
  java.lang.String getModule();
  /**
   * <code>optional string module = 1;</code>
   * @return The bytes for module.
   */
  com.google.protobuf.ByteString
      getModuleBytes();

  /**
   * <code>repeated .com.giyeok.tython.proto.Alias names = 2;</code>
   */
  java.util.List<com.giyeok.tython.proto.Alias> 
      getNamesList();
  /**
   * <code>repeated .com.giyeok.tython.proto.Alias names = 2;</code>
   */
  com.giyeok.tython.proto.Alias getNames(int index);
  /**
   * <code>repeated .com.giyeok.tython.proto.Alias names = 2;</code>
   */
  int getNamesCount();
  /**
   * <code>repeated .com.giyeok.tython.proto.Alias names = 2;</code>
   */
  java.util.List<? extends com.giyeok.tython.proto.AliasOrBuilder> 
      getNamesOrBuilderList();
  /**
   * <code>repeated .com.giyeok.tython.proto.Alias names = 2;</code>
   */
  com.giyeok.tython.proto.AliasOrBuilder getNamesOrBuilder(
      int index);

  /**
   * <code>optional int32 level = 3;</code>
   * @return Whether the level field is set.
   */
  boolean hasLevel();
  /**
   * <code>optional int32 level = 3;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <code>int32 lineno = 4;</code>
   * @return The lineno.
   */
  int getLineno();

  /**
   * <code>int32 col_offset = 5;</code>
   * @return The colOffset.
   */
  int getColOffset();

  /**
   * <code>optional int32 end_lineno = 6;</code>
   * @return Whether the endLineno field is set.
   */
  boolean hasEndLineno();
  /**
   * <code>optional int32 end_lineno = 6;</code>
   * @return The endLineno.
   */
  int getEndLineno();

  /**
   * <code>optional int32 end_col_offset = 7;</code>
   * @return Whether the endColOffset field is set.
   */
  boolean hasEndColOffset();
  /**
   * <code>optional int32 end_col_offset = 7;</code>
   * @return The endColOffset.
   */
  int getEndColOffset();
}
