// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: python3_10.proto

package com.giyeok.tython.proto;

/**
 * Protobuf type {@code com.giyeok.tython.proto.ListComp}
 */
public final class ListComp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.giyeok.tython.proto.ListComp)
    ListCompOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListComp.newBuilder() to construct.
  private ListComp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListComp() {
    generators_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListComp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListComp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.giyeok.tython.proto.AbstractExpr.Builder subBuilder = null;
            if (elt_ != null) {
              subBuilder = elt_.toBuilder();
            }
            elt_ = input.readMessage(com.giyeok.tython.proto.AbstractExpr.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(elt_);
              elt_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              generators_ = new java.util.ArrayList<com.giyeok.tython.proto.Comprehension>();
              mutable_bitField0_ |= 0x00000001;
            }
            generators_.add(
                input.readMessage(com.giyeok.tython.proto.Comprehension.parser(), extensionRegistry));
            break;
          }
          case 24: {

            lineno_ = input.readInt32();
            break;
          }
          case 32: {

            colOffset_ = input.readInt32();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000001;
            endLineno_ = input.readInt32();
            break;
          }
          case 48: {
            bitField0_ |= 0x00000002;
            endColOffset_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        generators_ = java.util.Collections.unmodifiableList(generators_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_ListComp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_ListComp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.giyeok.tython.proto.ListComp.class, com.giyeok.tython.proto.ListComp.Builder.class);
  }

  private int bitField0_;
  public static final int ELT_FIELD_NUMBER = 1;
  private com.giyeok.tython.proto.AbstractExpr elt_;
  /**
   * <code>.com.giyeok.tython.proto.AbstractExpr elt = 1;</code>
   * @return Whether the elt field is set.
   */
  @java.lang.Override
  public boolean hasElt() {
    return elt_ != null;
  }
  /**
   * <code>.com.giyeok.tython.proto.AbstractExpr elt = 1;</code>
   * @return The elt.
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractExpr getElt() {
    return elt_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : elt_;
  }
  /**
   * <code>.com.giyeok.tython.proto.AbstractExpr elt = 1;</code>
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractExprOrBuilder getEltOrBuilder() {
    return getElt();
  }

  public static final int GENERATORS_FIELD_NUMBER = 2;
  private java.util.List<com.giyeok.tython.proto.Comprehension> generators_;
  /**
   * <code>repeated .com.giyeok.tython.proto.Comprehension generators = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.giyeok.tython.proto.Comprehension> getGeneratorsList() {
    return generators_;
  }
  /**
   * <code>repeated .com.giyeok.tython.proto.Comprehension generators = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.giyeok.tython.proto.ComprehensionOrBuilder> 
      getGeneratorsOrBuilderList() {
    return generators_;
  }
  /**
   * <code>repeated .com.giyeok.tython.proto.Comprehension generators = 2;</code>
   */
  @java.lang.Override
  public int getGeneratorsCount() {
    return generators_.size();
  }
  /**
   * <code>repeated .com.giyeok.tython.proto.Comprehension generators = 2;</code>
   */
  @java.lang.Override
  public com.giyeok.tython.proto.Comprehension getGenerators(int index) {
    return generators_.get(index);
  }
  /**
   * <code>repeated .com.giyeok.tython.proto.Comprehension generators = 2;</code>
   */
  @java.lang.Override
  public com.giyeok.tython.proto.ComprehensionOrBuilder getGeneratorsOrBuilder(
      int index) {
    return generators_.get(index);
  }

  public static final int LINENO_FIELD_NUMBER = 3;
  private int lineno_;
  /**
   * <code>int32 lineno = 3;</code>
   * @return The lineno.
   */
  @java.lang.Override
  public int getLineno() {
    return lineno_;
  }

  public static final int COL_OFFSET_FIELD_NUMBER = 4;
  private int colOffset_;
  /**
   * <code>int32 col_offset = 4;</code>
   * @return The colOffset.
   */
  @java.lang.Override
  public int getColOffset() {
    return colOffset_;
  }

  public static final int END_LINENO_FIELD_NUMBER = 5;
  private int endLineno_;
  /**
   * <code>optional int32 end_lineno = 5;</code>
   * @return Whether the endLineno field is set.
   */
  @java.lang.Override
  public boolean hasEndLineno() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 end_lineno = 5;</code>
   * @return The endLineno.
   */
  @java.lang.Override
  public int getEndLineno() {
    return endLineno_;
  }

  public static final int END_COL_OFFSET_FIELD_NUMBER = 6;
  private int endColOffset_;
  /**
   * <code>optional int32 end_col_offset = 6;</code>
   * @return Whether the endColOffset field is set.
   */
  @java.lang.Override
  public boolean hasEndColOffset() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int32 end_col_offset = 6;</code>
   * @return The endColOffset.
   */
  @java.lang.Override
  public int getEndColOffset() {
    return endColOffset_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (elt_ != null) {
      output.writeMessage(1, getElt());
    }
    for (int i = 0; i < generators_.size(); i++) {
      output.writeMessage(2, generators_.get(i));
    }
    if (lineno_ != 0) {
      output.writeInt32(3, lineno_);
    }
    if (colOffset_ != 0) {
      output.writeInt32(4, colOffset_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(5, endLineno_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(6, endColOffset_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (elt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getElt());
    }
    for (int i = 0; i < generators_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, generators_.get(i));
    }
    if (lineno_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, lineno_);
    }
    if (colOffset_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, colOffset_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, endLineno_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, endColOffset_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.giyeok.tython.proto.ListComp)) {
      return super.equals(obj);
    }
    com.giyeok.tython.proto.ListComp other = (com.giyeok.tython.proto.ListComp) obj;

    if (hasElt() != other.hasElt()) return false;
    if (hasElt()) {
      if (!getElt()
          .equals(other.getElt())) return false;
    }
    if (!getGeneratorsList()
        .equals(other.getGeneratorsList())) return false;
    if (getLineno()
        != other.getLineno()) return false;
    if (getColOffset()
        != other.getColOffset()) return false;
    if (hasEndLineno() != other.hasEndLineno()) return false;
    if (hasEndLineno()) {
      if (getEndLineno()
          != other.getEndLineno()) return false;
    }
    if (hasEndColOffset() != other.hasEndColOffset()) return false;
    if (hasEndColOffset()) {
      if (getEndColOffset()
          != other.getEndColOffset()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasElt()) {
      hash = (37 * hash) + ELT_FIELD_NUMBER;
      hash = (53 * hash) + getElt().hashCode();
    }
    if (getGeneratorsCount() > 0) {
      hash = (37 * hash) + GENERATORS_FIELD_NUMBER;
      hash = (53 * hash) + getGeneratorsList().hashCode();
    }
    hash = (37 * hash) + LINENO_FIELD_NUMBER;
    hash = (53 * hash) + getLineno();
    hash = (37 * hash) + COL_OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + getColOffset();
    if (hasEndLineno()) {
      hash = (37 * hash) + END_LINENO_FIELD_NUMBER;
      hash = (53 * hash) + getEndLineno();
    }
    if (hasEndColOffset()) {
      hash = (37 * hash) + END_COL_OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + getEndColOffset();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.giyeok.tython.proto.ListComp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.giyeok.tython.proto.ListComp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.giyeok.tython.proto.ListComp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.giyeok.tython.proto.ListComp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.giyeok.tython.proto.ListComp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.giyeok.tython.proto.ListComp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.giyeok.tython.proto.ListComp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.giyeok.tython.proto.ListComp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.giyeok.tython.proto.ListComp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.giyeok.tython.proto.ListComp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.giyeok.tython.proto.ListComp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.giyeok.tython.proto.ListComp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.giyeok.tython.proto.ListComp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.giyeok.tython.proto.ListComp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.giyeok.tython.proto.ListComp)
      com.giyeok.tython.proto.ListCompOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_ListComp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_ListComp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.giyeok.tython.proto.ListComp.class, com.giyeok.tython.proto.ListComp.Builder.class);
    }

    // Construct using com.giyeok.tython.proto.ListComp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getGeneratorsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (eltBuilder_ == null) {
        elt_ = null;
      } else {
        elt_ = null;
        eltBuilder_ = null;
      }
      if (generatorsBuilder_ == null) {
        generators_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        generatorsBuilder_.clear();
      }
      lineno_ = 0;

      colOffset_ = 0;

      endLineno_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      endColOffset_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_ListComp_descriptor;
    }

    @java.lang.Override
    public com.giyeok.tython.proto.ListComp getDefaultInstanceForType() {
      return com.giyeok.tython.proto.ListComp.getDefaultInstance();
    }

    @java.lang.Override
    public com.giyeok.tython.proto.ListComp build() {
      com.giyeok.tython.proto.ListComp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.giyeok.tython.proto.ListComp buildPartial() {
      com.giyeok.tython.proto.ListComp result = new com.giyeok.tython.proto.ListComp(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (eltBuilder_ == null) {
        result.elt_ = elt_;
      } else {
        result.elt_ = eltBuilder_.build();
      }
      if (generatorsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          generators_ = java.util.Collections.unmodifiableList(generators_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.generators_ = generators_;
      } else {
        result.generators_ = generatorsBuilder_.build();
      }
      result.lineno_ = lineno_;
      result.colOffset_ = colOffset_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.endLineno_ = endLineno_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.endColOffset_ = endColOffset_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.giyeok.tython.proto.ListComp) {
        return mergeFrom((com.giyeok.tython.proto.ListComp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.giyeok.tython.proto.ListComp other) {
      if (other == com.giyeok.tython.proto.ListComp.getDefaultInstance()) return this;
      if (other.hasElt()) {
        mergeElt(other.getElt());
      }
      if (generatorsBuilder_ == null) {
        if (!other.generators_.isEmpty()) {
          if (generators_.isEmpty()) {
            generators_ = other.generators_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureGeneratorsIsMutable();
            generators_.addAll(other.generators_);
          }
          onChanged();
        }
      } else {
        if (!other.generators_.isEmpty()) {
          if (generatorsBuilder_.isEmpty()) {
            generatorsBuilder_.dispose();
            generatorsBuilder_ = null;
            generators_ = other.generators_;
            bitField0_ = (bitField0_ & ~0x00000001);
            generatorsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getGeneratorsFieldBuilder() : null;
          } else {
            generatorsBuilder_.addAllMessages(other.generators_);
          }
        }
      }
      if (other.getLineno() != 0) {
        setLineno(other.getLineno());
      }
      if (other.getColOffset() != 0) {
        setColOffset(other.getColOffset());
      }
      if (other.hasEndLineno()) {
        setEndLineno(other.getEndLineno());
      }
      if (other.hasEndColOffset()) {
        setEndColOffset(other.getEndColOffset());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.giyeok.tython.proto.ListComp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.giyeok.tython.proto.ListComp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.giyeok.tython.proto.AbstractExpr elt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder> eltBuilder_;
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr elt = 1;</code>
     * @return Whether the elt field is set.
     */
    public boolean hasElt() {
      return eltBuilder_ != null || elt_ != null;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr elt = 1;</code>
     * @return The elt.
     */
    public com.giyeok.tython.proto.AbstractExpr getElt() {
      if (eltBuilder_ == null) {
        return elt_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : elt_;
      } else {
        return eltBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr elt = 1;</code>
     */
    public Builder setElt(com.giyeok.tython.proto.AbstractExpr value) {
      if (eltBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        elt_ = value;
        onChanged();
      } else {
        eltBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr elt = 1;</code>
     */
    public Builder setElt(
        com.giyeok.tython.proto.AbstractExpr.Builder builderForValue) {
      if (eltBuilder_ == null) {
        elt_ = builderForValue.build();
        onChanged();
      } else {
        eltBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr elt = 1;</code>
     */
    public Builder mergeElt(com.giyeok.tython.proto.AbstractExpr value) {
      if (eltBuilder_ == null) {
        if (elt_ != null) {
          elt_ =
            com.giyeok.tython.proto.AbstractExpr.newBuilder(elt_).mergeFrom(value).buildPartial();
        } else {
          elt_ = value;
        }
        onChanged();
      } else {
        eltBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr elt = 1;</code>
     */
    public Builder clearElt() {
      if (eltBuilder_ == null) {
        elt_ = null;
        onChanged();
      } else {
        elt_ = null;
        eltBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr elt = 1;</code>
     */
    public com.giyeok.tython.proto.AbstractExpr.Builder getEltBuilder() {
      
      onChanged();
      return getEltFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr elt = 1;</code>
     */
    public com.giyeok.tython.proto.AbstractExprOrBuilder getEltOrBuilder() {
      if (eltBuilder_ != null) {
        return eltBuilder_.getMessageOrBuilder();
      } else {
        return elt_ == null ?
            com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : elt_;
      }
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr elt = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder> 
        getEltFieldBuilder() {
      if (eltBuilder_ == null) {
        eltBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder>(
                getElt(),
                getParentForChildren(),
                isClean());
        elt_ = null;
      }
      return eltBuilder_;
    }

    private java.util.List<com.giyeok.tython.proto.Comprehension> generators_ =
      java.util.Collections.emptyList();
    private void ensureGeneratorsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        generators_ = new java.util.ArrayList<com.giyeok.tython.proto.Comprehension>(generators_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.giyeok.tython.proto.Comprehension, com.giyeok.tython.proto.Comprehension.Builder, com.giyeok.tython.proto.ComprehensionOrBuilder> generatorsBuilder_;

    /**
     * <code>repeated .com.giyeok.tython.proto.Comprehension generators = 2;</code>
     */
    public java.util.List<com.giyeok.tython.proto.Comprehension> getGeneratorsList() {
      if (generatorsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(generators_);
      } else {
        return generatorsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.Comprehension generators = 2;</code>
     */
    public int getGeneratorsCount() {
      if (generatorsBuilder_ == null) {
        return generators_.size();
      } else {
        return generatorsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.Comprehension generators = 2;</code>
     */
    public com.giyeok.tython.proto.Comprehension getGenerators(int index) {
      if (generatorsBuilder_ == null) {
        return generators_.get(index);
      } else {
        return generatorsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.Comprehension generators = 2;</code>
     */
    public Builder setGenerators(
        int index, com.giyeok.tython.proto.Comprehension value) {
      if (generatorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGeneratorsIsMutable();
        generators_.set(index, value);
        onChanged();
      } else {
        generatorsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.Comprehension generators = 2;</code>
     */
    public Builder setGenerators(
        int index, com.giyeok.tython.proto.Comprehension.Builder builderForValue) {
      if (generatorsBuilder_ == null) {
        ensureGeneratorsIsMutable();
        generators_.set(index, builderForValue.build());
        onChanged();
      } else {
        generatorsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.Comprehension generators = 2;</code>
     */
    public Builder addGenerators(com.giyeok.tython.proto.Comprehension value) {
      if (generatorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGeneratorsIsMutable();
        generators_.add(value);
        onChanged();
      } else {
        generatorsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.Comprehension generators = 2;</code>
     */
    public Builder addGenerators(
        int index, com.giyeok.tython.proto.Comprehension value) {
      if (generatorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGeneratorsIsMutable();
        generators_.add(index, value);
        onChanged();
      } else {
        generatorsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.Comprehension generators = 2;</code>
     */
    public Builder addGenerators(
        com.giyeok.tython.proto.Comprehension.Builder builderForValue) {
      if (generatorsBuilder_ == null) {
        ensureGeneratorsIsMutable();
        generators_.add(builderForValue.build());
        onChanged();
      } else {
        generatorsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.Comprehension generators = 2;</code>
     */
    public Builder addGenerators(
        int index, com.giyeok.tython.proto.Comprehension.Builder builderForValue) {
      if (generatorsBuilder_ == null) {
        ensureGeneratorsIsMutable();
        generators_.add(index, builderForValue.build());
        onChanged();
      } else {
        generatorsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.Comprehension generators = 2;</code>
     */
    public Builder addAllGenerators(
        java.lang.Iterable<? extends com.giyeok.tython.proto.Comprehension> values) {
      if (generatorsBuilder_ == null) {
        ensureGeneratorsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, generators_);
        onChanged();
      } else {
        generatorsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.Comprehension generators = 2;</code>
     */
    public Builder clearGenerators() {
      if (generatorsBuilder_ == null) {
        generators_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        generatorsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.Comprehension generators = 2;</code>
     */
    public Builder removeGenerators(int index) {
      if (generatorsBuilder_ == null) {
        ensureGeneratorsIsMutable();
        generators_.remove(index);
        onChanged();
      } else {
        generatorsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.Comprehension generators = 2;</code>
     */
    public com.giyeok.tython.proto.Comprehension.Builder getGeneratorsBuilder(
        int index) {
      return getGeneratorsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.Comprehension generators = 2;</code>
     */
    public com.giyeok.tython.proto.ComprehensionOrBuilder getGeneratorsOrBuilder(
        int index) {
      if (generatorsBuilder_ == null) {
        return generators_.get(index);  } else {
        return generatorsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.Comprehension generators = 2;</code>
     */
    public java.util.List<? extends com.giyeok.tython.proto.ComprehensionOrBuilder> 
         getGeneratorsOrBuilderList() {
      if (generatorsBuilder_ != null) {
        return generatorsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(generators_);
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.Comprehension generators = 2;</code>
     */
    public com.giyeok.tython.proto.Comprehension.Builder addGeneratorsBuilder() {
      return getGeneratorsFieldBuilder().addBuilder(
          com.giyeok.tython.proto.Comprehension.getDefaultInstance());
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.Comprehension generators = 2;</code>
     */
    public com.giyeok.tython.proto.Comprehension.Builder addGeneratorsBuilder(
        int index) {
      return getGeneratorsFieldBuilder().addBuilder(
          index, com.giyeok.tython.proto.Comprehension.getDefaultInstance());
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.Comprehension generators = 2;</code>
     */
    public java.util.List<com.giyeok.tython.proto.Comprehension.Builder> 
         getGeneratorsBuilderList() {
      return getGeneratorsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.giyeok.tython.proto.Comprehension, com.giyeok.tython.proto.Comprehension.Builder, com.giyeok.tython.proto.ComprehensionOrBuilder> 
        getGeneratorsFieldBuilder() {
      if (generatorsBuilder_ == null) {
        generatorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.giyeok.tython.proto.Comprehension, com.giyeok.tython.proto.Comprehension.Builder, com.giyeok.tython.proto.ComprehensionOrBuilder>(
                generators_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        generators_ = null;
      }
      return generatorsBuilder_;
    }

    private int lineno_ ;
    /**
     * <code>int32 lineno = 3;</code>
     * @return The lineno.
     */
    @java.lang.Override
    public int getLineno() {
      return lineno_;
    }
    /**
     * <code>int32 lineno = 3;</code>
     * @param value The lineno to set.
     * @return This builder for chaining.
     */
    public Builder setLineno(int value) {
      
      lineno_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 lineno = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLineno() {
      
      lineno_ = 0;
      onChanged();
      return this;
    }

    private int colOffset_ ;
    /**
     * <code>int32 col_offset = 4;</code>
     * @return The colOffset.
     */
    @java.lang.Override
    public int getColOffset() {
      return colOffset_;
    }
    /**
     * <code>int32 col_offset = 4;</code>
     * @param value The colOffset to set.
     * @return This builder for chaining.
     */
    public Builder setColOffset(int value) {
      
      colOffset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 col_offset = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearColOffset() {
      
      colOffset_ = 0;
      onChanged();
      return this;
    }

    private int endLineno_ ;
    /**
     * <code>optional int32 end_lineno = 5;</code>
     * @return Whether the endLineno field is set.
     */
    @java.lang.Override
    public boolean hasEndLineno() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 end_lineno = 5;</code>
     * @return The endLineno.
     */
    @java.lang.Override
    public int getEndLineno() {
      return endLineno_;
    }
    /**
     * <code>optional int32 end_lineno = 5;</code>
     * @param value The endLineno to set.
     * @return This builder for chaining.
     */
    public Builder setEndLineno(int value) {
      bitField0_ |= 0x00000002;
      endLineno_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 end_lineno = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndLineno() {
      bitField0_ = (bitField0_ & ~0x00000002);
      endLineno_ = 0;
      onChanged();
      return this;
    }

    private int endColOffset_ ;
    /**
     * <code>optional int32 end_col_offset = 6;</code>
     * @return Whether the endColOffset field is set.
     */
    @java.lang.Override
    public boolean hasEndColOffset() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 end_col_offset = 6;</code>
     * @return The endColOffset.
     */
    @java.lang.Override
    public int getEndColOffset() {
      return endColOffset_;
    }
    /**
     * <code>optional int32 end_col_offset = 6;</code>
     * @param value The endColOffset to set.
     * @return This builder for chaining.
     */
    public Builder setEndColOffset(int value) {
      bitField0_ |= 0x00000004;
      endColOffset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 end_col_offset = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndColOffset() {
      bitField0_ = (bitField0_ & ~0x00000004);
      endColOffset_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.giyeok.tython.proto.ListComp)
  }

  // @@protoc_insertion_point(class_scope:com.giyeok.tython.proto.ListComp)
  private static final com.giyeok.tython.proto.ListComp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.giyeok.tython.proto.ListComp();
  }

  public static com.giyeok.tython.proto.ListComp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListComp>
      PARSER = new com.google.protobuf.AbstractParser<ListComp>() {
    @java.lang.Override
    public ListComp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListComp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListComp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListComp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.giyeok.tython.proto.ListComp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

