// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: python3_10.proto

package com.giyeok.tython.proto;

public interface MatchMappingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.giyeok.tython.proto.MatchMapping)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr keys = 1;</code>
   */
  java.util.List<com.giyeok.tython.proto.AbstractExpr> 
      getKeysList();
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr keys = 1;</code>
   */
  com.giyeok.tython.proto.AbstractExpr getKeys(int index);
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr keys = 1;</code>
   */
  int getKeysCount();
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr keys = 1;</code>
   */
  java.util.List<? extends com.giyeok.tython.proto.AbstractExprOrBuilder> 
      getKeysOrBuilderList();
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractExpr keys = 1;</code>
   */
  com.giyeok.tython.proto.AbstractExprOrBuilder getKeysOrBuilder(
      int index);

  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
   */
  java.util.List<com.giyeok.tython.proto.AbstractPattern> 
      getPatternsList();
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
   */
  com.giyeok.tython.proto.AbstractPattern getPatterns(int index);
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
   */
  int getPatternsCount();
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
   */
  java.util.List<? extends com.giyeok.tython.proto.AbstractPatternOrBuilder> 
      getPatternsOrBuilderList();
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
   */
  com.giyeok.tython.proto.AbstractPatternOrBuilder getPatternsOrBuilder(
      int index);

  /**
   * <code>optional string rest = 3;</code>
   * @return Whether the rest field is set.
   */
  boolean hasRest();
  /**
   * <code>optional string rest = 3;</code>
   * @return The rest.
   */
  java.lang.String getRest();
  /**
   * <code>optional string rest = 3;</code>
   * @return The bytes for rest.
   */
  com.google.protobuf.ByteString
      getRestBytes();

  /**
   * <code>int32 lineno = 4;</code>
   * @return The lineno.
   */
  int getLineno();

  /**
   * <code>int32 col_offset = 5;</code>
   * @return The colOffset.
   */
  int getColOffset();

  /**
   * <code>int32 end_lineno = 6;</code>
   * @return The endLineno.
   */
  int getEndLineno();

  /**
   * <code>int32 end_col_offset = 7;</code>
   * @return The endColOffset.
   */
  int getEndColOffset();
}
