// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: python3_10.proto

package com.giyeok.tython.proto;

/**
 * Protobuf type {@code com.giyeok.tython.proto.MatchClass}
 */
public final class MatchClass extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.giyeok.tython.proto.MatchClass)
    MatchClassOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MatchClass.newBuilder() to construct.
  private MatchClass(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MatchClass() {
    patterns_ = java.util.Collections.emptyList();
    kwdAttrs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    kwdPatterns_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MatchClass();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MatchClass(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.giyeok.tython.proto.AbstractExpr.Builder subBuilder = null;
            if (cls_ != null) {
              subBuilder = cls_.toBuilder();
            }
            cls_ = input.readMessage(com.giyeok.tython.proto.AbstractExpr.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(cls_);
              cls_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              patterns_ = new java.util.ArrayList<com.giyeok.tython.proto.AbstractPattern>();
              mutable_bitField0_ |= 0x00000001;
            }
            patterns_.add(
                input.readMessage(com.giyeok.tython.proto.AbstractPattern.parser(), extensionRegistry));
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              kwdAttrs_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            kwdAttrs_.add(s);
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              kwdPatterns_ = new java.util.ArrayList<com.giyeok.tython.proto.AbstractPattern>();
              mutable_bitField0_ |= 0x00000004;
            }
            kwdPatterns_.add(
                input.readMessage(com.giyeok.tython.proto.AbstractPattern.parser(), extensionRegistry));
            break;
          }
          case 40: {

            lineno_ = input.readInt32();
            break;
          }
          case 48: {

            colOffset_ = input.readInt32();
            break;
          }
          case 56: {

            endLineno_ = input.readInt32();
            break;
          }
          case 64: {

            endColOffset_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        patterns_ = java.util.Collections.unmodifiableList(patterns_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        kwdAttrs_ = kwdAttrs_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        kwdPatterns_ = java.util.Collections.unmodifiableList(kwdPatterns_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_MatchClass_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_MatchClass_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.giyeok.tython.proto.MatchClass.class, com.giyeok.tython.proto.MatchClass.Builder.class);
  }

  public static final int CLS_FIELD_NUMBER = 1;
  private com.giyeok.tython.proto.AbstractExpr cls_;
  /**
   * <code>.com.giyeok.tython.proto.AbstractExpr cls = 1;</code>
   * @return Whether the cls field is set.
   */
  @java.lang.Override
  public boolean hasCls() {
    return cls_ != null;
  }
  /**
   * <code>.com.giyeok.tython.proto.AbstractExpr cls = 1;</code>
   * @return The cls.
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractExpr getCls() {
    return cls_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : cls_;
  }
  /**
   * <code>.com.giyeok.tython.proto.AbstractExpr cls = 1;</code>
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractExprOrBuilder getClsOrBuilder() {
    return getCls();
  }

  public static final int PATTERNS_FIELD_NUMBER = 2;
  private java.util.List<com.giyeok.tython.proto.AbstractPattern> patterns_;
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.giyeok.tython.proto.AbstractPattern> getPatternsList() {
    return patterns_;
  }
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.giyeok.tython.proto.AbstractPatternOrBuilder> 
      getPatternsOrBuilderList() {
    return patterns_;
  }
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
   */
  @java.lang.Override
  public int getPatternsCount() {
    return patterns_.size();
  }
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractPattern getPatterns(int index) {
    return patterns_.get(index);
  }
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractPatternOrBuilder getPatternsOrBuilder(
      int index) {
    return patterns_.get(index);
  }

  public static final int KWD_ATTRS_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList kwdAttrs_;
  /**
   * <code>repeated string kwd_attrs = 3;</code>
   * @return A list containing the kwdAttrs.
   */
  public com.google.protobuf.ProtocolStringList
      getKwdAttrsList() {
    return kwdAttrs_;
  }
  /**
   * <code>repeated string kwd_attrs = 3;</code>
   * @return The count of kwdAttrs.
   */
  public int getKwdAttrsCount() {
    return kwdAttrs_.size();
  }
  /**
   * <code>repeated string kwd_attrs = 3;</code>
   * @param index The index of the element to return.
   * @return The kwdAttrs at the given index.
   */
  public java.lang.String getKwdAttrs(int index) {
    return kwdAttrs_.get(index);
  }
  /**
   * <code>repeated string kwd_attrs = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the kwdAttrs at the given index.
   */
  public com.google.protobuf.ByteString
      getKwdAttrsBytes(int index) {
    return kwdAttrs_.getByteString(index);
  }

  public static final int KWD_PATTERNS_FIELD_NUMBER = 4;
  private java.util.List<com.giyeok.tython.proto.AbstractPattern> kwdPatterns_;
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractPattern kwd_patterns = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.giyeok.tython.proto.AbstractPattern> getKwdPatternsList() {
    return kwdPatterns_;
  }
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractPattern kwd_patterns = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.giyeok.tython.proto.AbstractPatternOrBuilder> 
      getKwdPatternsOrBuilderList() {
    return kwdPatterns_;
  }
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractPattern kwd_patterns = 4;</code>
   */
  @java.lang.Override
  public int getKwdPatternsCount() {
    return kwdPatterns_.size();
  }
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractPattern kwd_patterns = 4;</code>
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractPattern getKwdPatterns(int index) {
    return kwdPatterns_.get(index);
  }
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractPattern kwd_patterns = 4;</code>
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractPatternOrBuilder getKwdPatternsOrBuilder(
      int index) {
    return kwdPatterns_.get(index);
  }

  public static final int LINENO_FIELD_NUMBER = 5;
  private int lineno_;
  /**
   * <code>int32 lineno = 5;</code>
   * @return The lineno.
   */
  @java.lang.Override
  public int getLineno() {
    return lineno_;
  }

  public static final int COL_OFFSET_FIELD_NUMBER = 6;
  private int colOffset_;
  /**
   * <code>int32 col_offset = 6;</code>
   * @return The colOffset.
   */
  @java.lang.Override
  public int getColOffset() {
    return colOffset_;
  }

  public static final int END_LINENO_FIELD_NUMBER = 7;
  private int endLineno_;
  /**
   * <code>int32 end_lineno = 7;</code>
   * @return The endLineno.
   */
  @java.lang.Override
  public int getEndLineno() {
    return endLineno_;
  }

  public static final int END_COL_OFFSET_FIELD_NUMBER = 8;
  private int endColOffset_;
  /**
   * <code>int32 end_col_offset = 8;</code>
   * @return The endColOffset.
   */
  @java.lang.Override
  public int getEndColOffset() {
    return endColOffset_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (cls_ != null) {
      output.writeMessage(1, getCls());
    }
    for (int i = 0; i < patterns_.size(); i++) {
      output.writeMessage(2, patterns_.get(i));
    }
    for (int i = 0; i < kwdAttrs_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, kwdAttrs_.getRaw(i));
    }
    for (int i = 0; i < kwdPatterns_.size(); i++) {
      output.writeMessage(4, kwdPatterns_.get(i));
    }
    if (lineno_ != 0) {
      output.writeInt32(5, lineno_);
    }
    if (colOffset_ != 0) {
      output.writeInt32(6, colOffset_);
    }
    if (endLineno_ != 0) {
      output.writeInt32(7, endLineno_);
    }
    if (endColOffset_ != 0) {
      output.writeInt32(8, endColOffset_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (cls_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCls());
    }
    for (int i = 0; i < patterns_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, patterns_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < kwdAttrs_.size(); i++) {
        dataSize += computeStringSizeNoTag(kwdAttrs_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getKwdAttrsList().size();
    }
    for (int i = 0; i < kwdPatterns_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, kwdPatterns_.get(i));
    }
    if (lineno_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, lineno_);
    }
    if (colOffset_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, colOffset_);
    }
    if (endLineno_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, endLineno_);
    }
    if (endColOffset_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, endColOffset_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.giyeok.tython.proto.MatchClass)) {
      return super.equals(obj);
    }
    com.giyeok.tython.proto.MatchClass other = (com.giyeok.tython.proto.MatchClass) obj;

    if (hasCls() != other.hasCls()) return false;
    if (hasCls()) {
      if (!getCls()
          .equals(other.getCls())) return false;
    }
    if (!getPatternsList()
        .equals(other.getPatternsList())) return false;
    if (!getKwdAttrsList()
        .equals(other.getKwdAttrsList())) return false;
    if (!getKwdPatternsList()
        .equals(other.getKwdPatternsList())) return false;
    if (getLineno()
        != other.getLineno()) return false;
    if (getColOffset()
        != other.getColOffset()) return false;
    if (getEndLineno()
        != other.getEndLineno()) return false;
    if (getEndColOffset()
        != other.getEndColOffset()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCls()) {
      hash = (37 * hash) + CLS_FIELD_NUMBER;
      hash = (53 * hash) + getCls().hashCode();
    }
    if (getPatternsCount() > 0) {
      hash = (37 * hash) + PATTERNS_FIELD_NUMBER;
      hash = (53 * hash) + getPatternsList().hashCode();
    }
    if (getKwdAttrsCount() > 0) {
      hash = (37 * hash) + KWD_ATTRS_FIELD_NUMBER;
      hash = (53 * hash) + getKwdAttrsList().hashCode();
    }
    if (getKwdPatternsCount() > 0) {
      hash = (37 * hash) + KWD_PATTERNS_FIELD_NUMBER;
      hash = (53 * hash) + getKwdPatternsList().hashCode();
    }
    hash = (37 * hash) + LINENO_FIELD_NUMBER;
    hash = (53 * hash) + getLineno();
    hash = (37 * hash) + COL_OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + getColOffset();
    hash = (37 * hash) + END_LINENO_FIELD_NUMBER;
    hash = (53 * hash) + getEndLineno();
    hash = (37 * hash) + END_COL_OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + getEndColOffset();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.giyeok.tython.proto.MatchClass parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.giyeok.tython.proto.MatchClass parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.giyeok.tython.proto.MatchClass parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.giyeok.tython.proto.MatchClass parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.giyeok.tython.proto.MatchClass parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.giyeok.tython.proto.MatchClass parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.giyeok.tython.proto.MatchClass parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.giyeok.tython.proto.MatchClass parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.giyeok.tython.proto.MatchClass parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.giyeok.tython.proto.MatchClass parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.giyeok.tython.proto.MatchClass parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.giyeok.tython.proto.MatchClass parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.giyeok.tython.proto.MatchClass prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.giyeok.tython.proto.MatchClass}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.giyeok.tython.proto.MatchClass)
      com.giyeok.tython.proto.MatchClassOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_MatchClass_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_MatchClass_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.giyeok.tython.proto.MatchClass.class, com.giyeok.tython.proto.MatchClass.Builder.class);
    }

    // Construct using com.giyeok.tython.proto.MatchClass.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPatternsFieldBuilder();
        getKwdPatternsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (clsBuilder_ == null) {
        cls_ = null;
      } else {
        cls_ = null;
        clsBuilder_ = null;
      }
      if (patternsBuilder_ == null) {
        patterns_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        patternsBuilder_.clear();
      }
      kwdAttrs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      if (kwdPatternsBuilder_ == null) {
        kwdPatterns_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        kwdPatternsBuilder_.clear();
      }
      lineno_ = 0;

      colOffset_ = 0;

      endLineno_ = 0;

      endColOffset_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_MatchClass_descriptor;
    }

    @java.lang.Override
    public com.giyeok.tython.proto.MatchClass getDefaultInstanceForType() {
      return com.giyeok.tython.proto.MatchClass.getDefaultInstance();
    }

    @java.lang.Override
    public com.giyeok.tython.proto.MatchClass build() {
      com.giyeok.tython.proto.MatchClass result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.giyeok.tython.proto.MatchClass buildPartial() {
      com.giyeok.tython.proto.MatchClass result = new com.giyeok.tython.proto.MatchClass(this);
      int from_bitField0_ = bitField0_;
      if (clsBuilder_ == null) {
        result.cls_ = cls_;
      } else {
        result.cls_ = clsBuilder_.build();
      }
      if (patternsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          patterns_ = java.util.Collections.unmodifiableList(patterns_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.patterns_ = patterns_;
      } else {
        result.patterns_ = patternsBuilder_.build();
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        kwdAttrs_ = kwdAttrs_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.kwdAttrs_ = kwdAttrs_;
      if (kwdPatternsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          kwdPatterns_ = java.util.Collections.unmodifiableList(kwdPatterns_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.kwdPatterns_ = kwdPatterns_;
      } else {
        result.kwdPatterns_ = kwdPatternsBuilder_.build();
      }
      result.lineno_ = lineno_;
      result.colOffset_ = colOffset_;
      result.endLineno_ = endLineno_;
      result.endColOffset_ = endColOffset_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.giyeok.tython.proto.MatchClass) {
        return mergeFrom((com.giyeok.tython.proto.MatchClass)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.giyeok.tython.proto.MatchClass other) {
      if (other == com.giyeok.tython.proto.MatchClass.getDefaultInstance()) return this;
      if (other.hasCls()) {
        mergeCls(other.getCls());
      }
      if (patternsBuilder_ == null) {
        if (!other.patterns_.isEmpty()) {
          if (patterns_.isEmpty()) {
            patterns_ = other.patterns_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePatternsIsMutable();
            patterns_.addAll(other.patterns_);
          }
          onChanged();
        }
      } else {
        if (!other.patterns_.isEmpty()) {
          if (patternsBuilder_.isEmpty()) {
            patternsBuilder_.dispose();
            patternsBuilder_ = null;
            patterns_ = other.patterns_;
            bitField0_ = (bitField0_ & ~0x00000001);
            patternsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPatternsFieldBuilder() : null;
          } else {
            patternsBuilder_.addAllMessages(other.patterns_);
          }
        }
      }
      if (!other.kwdAttrs_.isEmpty()) {
        if (kwdAttrs_.isEmpty()) {
          kwdAttrs_ = other.kwdAttrs_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureKwdAttrsIsMutable();
          kwdAttrs_.addAll(other.kwdAttrs_);
        }
        onChanged();
      }
      if (kwdPatternsBuilder_ == null) {
        if (!other.kwdPatterns_.isEmpty()) {
          if (kwdPatterns_.isEmpty()) {
            kwdPatterns_ = other.kwdPatterns_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureKwdPatternsIsMutable();
            kwdPatterns_.addAll(other.kwdPatterns_);
          }
          onChanged();
        }
      } else {
        if (!other.kwdPatterns_.isEmpty()) {
          if (kwdPatternsBuilder_.isEmpty()) {
            kwdPatternsBuilder_.dispose();
            kwdPatternsBuilder_ = null;
            kwdPatterns_ = other.kwdPatterns_;
            bitField0_ = (bitField0_ & ~0x00000004);
            kwdPatternsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getKwdPatternsFieldBuilder() : null;
          } else {
            kwdPatternsBuilder_.addAllMessages(other.kwdPatterns_);
          }
        }
      }
      if (other.getLineno() != 0) {
        setLineno(other.getLineno());
      }
      if (other.getColOffset() != 0) {
        setColOffset(other.getColOffset());
      }
      if (other.getEndLineno() != 0) {
        setEndLineno(other.getEndLineno());
      }
      if (other.getEndColOffset() != 0) {
        setEndColOffset(other.getEndColOffset());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.giyeok.tython.proto.MatchClass parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.giyeok.tython.proto.MatchClass) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.giyeok.tython.proto.AbstractExpr cls_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder> clsBuilder_;
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr cls = 1;</code>
     * @return Whether the cls field is set.
     */
    public boolean hasCls() {
      return clsBuilder_ != null || cls_ != null;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr cls = 1;</code>
     * @return The cls.
     */
    public com.giyeok.tython.proto.AbstractExpr getCls() {
      if (clsBuilder_ == null) {
        return cls_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : cls_;
      } else {
        return clsBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr cls = 1;</code>
     */
    public Builder setCls(com.giyeok.tython.proto.AbstractExpr value) {
      if (clsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cls_ = value;
        onChanged();
      } else {
        clsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr cls = 1;</code>
     */
    public Builder setCls(
        com.giyeok.tython.proto.AbstractExpr.Builder builderForValue) {
      if (clsBuilder_ == null) {
        cls_ = builderForValue.build();
        onChanged();
      } else {
        clsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr cls = 1;</code>
     */
    public Builder mergeCls(com.giyeok.tython.proto.AbstractExpr value) {
      if (clsBuilder_ == null) {
        if (cls_ != null) {
          cls_ =
            com.giyeok.tython.proto.AbstractExpr.newBuilder(cls_).mergeFrom(value).buildPartial();
        } else {
          cls_ = value;
        }
        onChanged();
      } else {
        clsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr cls = 1;</code>
     */
    public Builder clearCls() {
      if (clsBuilder_ == null) {
        cls_ = null;
        onChanged();
      } else {
        cls_ = null;
        clsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr cls = 1;</code>
     */
    public com.giyeok.tython.proto.AbstractExpr.Builder getClsBuilder() {
      
      onChanged();
      return getClsFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr cls = 1;</code>
     */
    public com.giyeok.tython.proto.AbstractExprOrBuilder getClsOrBuilder() {
      if (clsBuilder_ != null) {
        return clsBuilder_.getMessageOrBuilder();
      } else {
        return cls_ == null ?
            com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : cls_;
      }
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr cls = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder> 
        getClsFieldBuilder() {
      if (clsBuilder_ == null) {
        clsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder>(
                getCls(),
                getParentForChildren(),
                isClean());
        cls_ = null;
      }
      return clsBuilder_;
    }

    private java.util.List<com.giyeok.tython.proto.AbstractPattern> patterns_ =
      java.util.Collections.emptyList();
    private void ensurePatternsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        patterns_ = new java.util.ArrayList<com.giyeok.tython.proto.AbstractPattern>(patterns_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.giyeok.tython.proto.AbstractPattern, com.giyeok.tython.proto.AbstractPattern.Builder, com.giyeok.tython.proto.AbstractPatternOrBuilder> patternsBuilder_;

    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
     */
    public java.util.List<com.giyeok.tython.proto.AbstractPattern> getPatternsList() {
      if (patternsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(patterns_);
      } else {
        return patternsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
     */
    public int getPatternsCount() {
      if (patternsBuilder_ == null) {
        return patterns_.size();
      } else {
        return patternsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
     */
    public com.giyeok.tython.proto.AbstractPattern getPatterns(int index) {
      if (patternsBuilder_ == null) {
        return patterns_.get(index);
      } else {
        return patternsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
     */
    public Builder setPatterns(
        int index, com.giyeok.tython.proto.AbstractPattern value) {
      if (patternsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePatternsIsMutable();
        patterns_.set(index, value);
        onChanged();
      } else {
        patternsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
     */
    public Builder setPatterns(
        int index, com.giyeok.tython.proto.AbstractPattern.Builder builderForValue) {
      if (patternsBuilder_ == null) {
        ensurePatternsIsMutable();
        patterns_.set(index, builderForValue.build());
        onChanged();
      } else {
        patternsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
     */
    public Builder addPatterns(com.giyeok.tython.proto.AbstractPattern value) {
      if (patternsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePatternsIsMutable();
        patterns_.add(value);
        onChanged();
      } else {
        patternsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
     */
    public Builder addPatterns(
        int index, com.giyeok.tython.proto.AbstractPattern value) {
      if (patternsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePatternsIsMutable();
        patterns_.add(index, value);
        onChanged();
      } else {
        patternsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
     */
    public Builder addPatterns(
        com.giyeok.tython.proto.AbstractPattern.Builder builderForValue) {
      if (patternsBuilder_ == null) {
        ensurePatternsIsMutable();
        patterns_.add(builderForValue.build());
        onChanged();
      } else {
        patternsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
     */
    public Builder addPatterns(
        int index, com.giyeok.tython.proto.AbstractPattern.Builder builderForValue) {
      if (patternsBuilder_ == null) {
        ensurePatternsIsMutable();
        patterns_.add(index, builderForValue.build());
        onChanged();
      } else {
        patternsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
     */
    public Builder addAllPatterns(
        java.lang.Iterable<? extends com.giyeok.tython.proto.AbstractPattern> values) {
      if (patternsBuilder_ == null) {
        ensurePatternsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, patterns_);
        onChanged();
      } else {
        patternsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
     */
    public Builder clearPatterns() {
      if (patternsBuilder_ == null) {
        patterns_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        patternsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
     */
    public Builder removePatterns(int index) {
      if (patternsBuilder_ == null) {
        ensurePatternsIsMutable();
        patterns_.remove(index);
        onChanged();
      } else {
        patternsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
     */
    public com.giyeok.tython.proto.AbstractPattern.Builder getPatternsBuilder(
        int index) {
      return getPatternsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
     */
    public com.giyeok.tython.proto.AbstractPatternOrBuilder getPatternsOrBuilder(
        int index) {
      if (patternsBuilder_ == null) {
        return patterns_.get(index);  } else {
        return patternsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
     */
    public java.util.List<? extends com.giyeok.tython.proto.AbstractPatternOrBuilder> 
         getPatternsOrBuilderList() {
      if (patternsBuilder_ != null) {
        return patternsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(patterns_);
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
     */
    public com.giyeok.tython.proto.AbstractPattern.Builder addPatternsBuilder() {
      return getPatternsFieldBuilder().addBuilder(
          com.giyeok.tython.proto.AbstractPattern.getDefaultInstance());
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
     */
    public com.giyeok.tython.proto.AbstractPattern.Builder addPatternsBuilder(
        int index) {
      return getPatternsFieldBuilder().addBuilder(
          index, com.giyeok.tython.proto.AbstractPattern.getDefaultInstance());
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern patterns = 2;</code>
     */
    public java.util.List<com.giyeok.tython.proto.AbstractPattern.Builder> 
         getPatternsBuilderList() {
      return getPatternsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.giyeok.tython.proto.AbstractPattern, com.giyeok.tython.proto.AbstractPattern.Builder, com.giyeok.tython.proto.AbstractPatternOrBuilder> 
        getPatternsFieldBuilder() {
      if (patternsBuilder_ == null) {
        patternsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.giyeok.tython.proto.AbstractPattern, com.giyeok.tython.proto.AbstractPattern.Builder, com.giyeok.tython.proto.AbstractPatternOrBuilder>(
                patterns_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        patterns_ = null;
      }
      return patternsBuilder_;
    }

    private com.google.protobuf.LazyStringList kwdAttrs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureKwdAttrsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        kwdAttrs_ = new com.google.protobuf.LazyStringArrayList(kwdAttrs_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string kwd_attrs = 3;</code>
     * @return A list containing the kwdAttrs.
     */
    public com.google.protobuf.ProtocolStringList
        getKwdAttrsList() {
      return kwdAttrs_.getUnmodifiableView();
    }
    /**
     * <code>repeated string kwd_attrs = 3;</code>
     * @return The count of kwdAttrs.
     */
    public int getKwdAttrsCount() {
      return kwdAttrs_.size();
    }
    /**
     * <code>repeated string kwd_attrs = 3;</code>
     * @param index The index of the element to return.
     * @return The kwdAttrs at the given index.
     */
    public java.lang.String getKwdAttrs(int index) {
      return kwdAttrs_.get(index);
    }
    /**
     * <code>repeated string kwd_attrs = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the kwdAttrs at the given index.
     */
    public com.google.protobuf.ByteString
        getKwdAttrsBytes(int index) {
      return kwdAttrs_.getByteString(index);
    }
    /**
     * <code>repeated string kwd_attrs = 3;</code>
     * @param index The index to set the value at.
     * @param value The kwdAttrs to set.
     * @return This builder for chaining.
     */
    public Builder setKwdAttrs(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureKwdAttrsIsMutable();
      kwdAttrs_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string kwd_attrs = 3;</code>
     * @param value The kwdAttrs to add.
     * @return This builder for chaining.
     */
    public Builder addKwdAttrs(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureKwdAttrsIsMutable();
      kwdAttrs_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string kwd_attrs = 3;</code>
     * @param values The kwdAttrs to add.
     * @return This builder for chaining.
     */
    public Builder addAllKwdAttrs(
        java.lang.Iterable<java.lang.String> values) {
      ensureKwdAttrsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, kwdAttrs_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string kwd_attrs = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearKwdAttrs() {
      kwdAttrs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string kwd_attrs = 3;</code>
     * @param value The bytes of the kwdAttrs to add.
     * @return This builder for chaining.
     */
    public Builder addKwdAttrsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureKwdAttrsIsMutable();
      kwdAttrs_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<com.giyeok.tython.proto.AbstractPattern> kwdPatterns_ =
      java.util.Collections.emptyList();
    private void ensureKwdPatternsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        kwdPatterns_ = new java.util.ArrayList<com.giyeok.tython.proto.AbstractPattern>(kwdPatterns_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.giyeok.tython.proto.AbstractPattern, com.giyeok.tython.proto.AbstractPattern.Builder, com.giyeok.tython.proto.AbstractPatternOrBuilder> kwdPatternsBuilder_;

    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern kwd_patterns = 4;</code>
     */
    public java.util.List<com.giyeok.tython.proto.AbstractPattern> getKwdPatternsList() {
      if (kwdPatternsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(kwdPatterns_);
      } else {
        return kwdPatternsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern kwd_patterns = 4;</code>
     */
    public int getKwdPatternsCount() {
      if (kwdPatternsBuilder_ == null) {
        return kwdPatterns_.size();
      } else {
        return kwdPatternsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern kwd_patterns = 4;</code>
     */
    public com.giyeok.tython.proto.AbstractPattern getKwdPatterns(int index) {
      if (kwdPatternsBuilder_ == null) {
        return kwdPatterns_.get(index);
      } else {
        return kwdPatternsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern kwd_patterns = 4;</code>
     */
    public Builder setKwdPatterns(
        int index, com.giyeok.tython.proto.AbstractPattern value) {
      if (kwdPatternsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKwdPatternsIsMutable();
        kwdPatterns_.set(index, value);
        onChanged();
      } else {
        kwdPatternsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern kwd_patterns = 4;</code>
     */
    public Builder setKwdPatterns(
        int index, com.giyeok.tython.proto.AbstractPattern.Builder builderForValue) {
      if (kwdPatternsBuilder_ == null) {
        ensureKwdPatternsIsMutable();
        kwdPatterns_.set(index, builderForValue.build());
        onChanged();
      } else {
        kwdPatternsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern kwd_patterns = 4;</code>
     */
    public Builder addKwdPatterns(com.giyeok.tython.proto.AbstractPattern value) {
      if (kwdPatternsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKwdPatternsIsMutable();
        kwdPatterns_.add(value);
        onChanged();
      } else {
        kwdPatternsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern kwd_patterns = 4;</code>
     */
    public Builder addKwdPatterns(
        int index, com.giyeok.tython.proto.AbstractPattern value) {
      if (kwdPatternsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKwdPatternsIsMutable();
        kwdPatterns_.add(index, value);
        onChanged();
      } else {
        kwdPatternsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern kwd_patterns = 4;</code>
     */
    public Builder addKwdPatterns(
        com.giyeok.tython.proto.AbstractPattern.Builder builderForValue) {
      if (kwdPatternsBuilder_ == null) {
        ensureKwdPatternsIsMutable();
        kwdPatterns_.add(builderForValue.build());
        onChanged();
      } else {
        kwdPatternsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern kwd_patterns = 4;</code>
     */
    public Builder addKwdPatterns(
        int index, com.giyeok.tython.proto.AbstractPattern.Builder builderForValue) {
      if (kwdPatternsBuilder_ == null) {
        ensureKwdPatternsIsMutable();
        kwdPatterns_.add(index, builderForValue.build());
        onChanged();
      } else {
        kwdPatternsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern kwd_patterns = 4;</code>
     */
    public Builder addAllKwdPatterns(
        java.lang.Iterable<? extends com.giyeok.tython.proto.AbstractPattern> values) {
      if (kwdPatternsBuilder_ == null) {
        ensureKwdPatternsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, kwdPatterns_);
        onChanged();
      } else {
        kwdPatternsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern kwd_patterns = 4;</code>
     */
    public Builder clearKwdPatterns() {
      if (kwdPatternsBuilder_ == null) {
        kwdPatterns_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        kwdPatternsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern kwd_patterns = 4;</code>
     */
    public Builder removeKwdPatterns(int index) {
      if (kwdPatternsBuilder_ == null) {
        ensureKwdPatternsIsMutable();
        kwdPatterns_.remove(index);
        onChanged();
      } else {
        kwdPatternsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern kwd_patterns = 4;</code>
     */
    public com.giyeok.tython.proto.AbstractPattern.Builder getKwdPatternsBuilder(
        int index) {
      return getKwdPatternsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern kwd_patterns = 4;</code>
     */
    public com.giyeok.tython.proto.AbstractPatternOrBuilder getKwdPatternsOrBuilder(
        int index) {
      if (kwdPatternsBuilder_ == null) {
        return kwdPatterns_.get(index);  } else {
        return kwdPatternsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern kwd_patterns = 4;</code>
     */
    public java.util.List<? extends com.giyeok.tython.proto.AbstractPatternOrBuilder> 
         getKwdPatternsOrBuilderList() {
      if (kwdPatternsBuilder_ != null) {
        return kwdPatternsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(kwdPatterns_);
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern kwd_patterns = 4;</code>
     */
    public com.giyeok.tython.proto.AbstractPattern.Builder addKwdPatternsBuilder() {
      return getKwdPatternsFieldBuilder().addBuilder(
          com.giyeok.tython.proto.AbstractPattern.getDefaultInstance());
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern kwd_patterns = 4;</code>
     */
    public com.giyeok.tython.proto.AbstractPattern.Builder addKwdPatternsBuilder(
        int index) {
      return getKwdPatternsFieldBuilder().addBuilder(
          index, com.giyeok.tython.proto.AbstractPattern.getDefaultInstance());
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractPattern kwd_patterns = 4;</code>
     */
    public java.util.List<com.giyeok.tython.proto.AbstractPattern.Builder> 
         getKwdPatternsBuilderList() {
      return getKwdPatternsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.giyeok.tython.proto.AbstractPattern, com.giyeok.tython.proto.AbstractPattern.Builder, com.giyeok.tython.proto.AbstractPatternOrBuilder> 
        getKwdPatternsFieldBuilder() {
      if (kwdPatternsBuilder_ == null) {
        kwdPatternsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.giyeok.tython.proto.AbstractPattern, com.giyeok.tython.proto.AbstractPattern.Builder, com.giyeok.tython.proto.AbstractPatternOrBuilder>(
                kwdPatterns_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        kwdPatterns_ = null;
      }
      return kwdPatternsBuilder_;
    }

    private int lineno_ ;
    /**
     * <code>int32 lineno = 5;</code>
     * @return The lineno.
     */
    @java.lang.Override
    public int getLineno() {
      return lineno_;
    }
    /**
     * <code>int32 lineno = 5;</code>
     * @param value The lineno to set.
     * @return This builder for chaining.
     */
    public Builder setLineno(int value) {
      
      lineno_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 lineno = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLineno() {
      
      lineno_ = 0;
      onChanged();
      return this;
    }

    private int colOffset_ ;
    /**
     * <code>int32 col_offset = 6;</code>
     * @return The colOffset.
     */
    @java.lang.Override
    public int getColOffset() {
      return colOffset_;
    }
    /**
     * <code>int32 col_offset = 6;</code>
     * @param value The colOffset to set.
     * @return This builder for chaining.
     */
    public Builder setColOffset(int value) {
      
      colOffset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 col_offset = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearColOffset() {
      
      colOffset_ = 0;
      onChanged();
      return this;
    }

    private int endLineno_ ;
    /**
     * <code>int32 end_lineno = 7;</code>
     * @return The endLineno.
     */
    @java.lang.Override
    public int getEndLineno() {
      return endLineno_;
    }
    /**
     * <code>int32 end_lineno = 7;</code>
     * @param value The endLineno to set.
     * @return This builder for chaining.
     */
    public Builder setEndLineno(int value) {
      
      endLineno_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 end_lineno = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndLineno() {
      
      endLineno_ = 0;
      onChanged();
      return this;
    }

    private int endColOffset_ ;
    /**
     * <code>int32 end_col_offset = 8;</code>
     * @return The endColOffset.
     */
    @java.lang.Override
    public int getEndColOffset() {
      return endColOffset_;
    }
    /**
     * <code>int32 end_col_offset = 8;</code>
     * @param value The endColOffset to set.
     * @return This builder for chaining.
     */
    public Builder setEndColOffset(int value) {
      
      endColOffset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 end_col_offset = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndColOffset() {
      
      endColOffset_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.giyeok.tython.proto.MatchClass)
  }

  // @@protoc_insertion_point(class_scope:com.giyeok.tython.proto.MatchClass)
  private static final com.giyeok.tython.proto.MatchClass DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.giyeok.tython.proto.MatchClass();
  }

  public static com.giyeok.tython.proto.MatchClass getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MatchClass>
      PARSER = new com.google.protobuf.AbstractParser<MatchClass>() {
    @java.lang.Override
    public MatchClass parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MatchClass(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MatchClass> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MatchClass> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.giyeok.tython.proto.MatchClass getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

