// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: python3_10.proto

package com.giyeok.tython.proto;

/**
 * Protobuf type {@code com.giyeok.tython.proto.MatchCase}
 */
public final class MatchCase extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.giyeok.tython.proto.MatchCase)
    MatchCaseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MatchCase.newBuilder() to construct.
  private MatchCase(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MatchCase() {
    body_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MatchCase();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MatchCase(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.giyeok.tython.proto.AbstractPattern.Builder subBuilder = null;
            if (pattern_ != null) {
              subBuilder = pattern_.toBuilder();
            }
            pattern_ = input.readMessage(com.giyeok.tython.proto.AbstractPattern.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pattern_);
              pattern_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.giyeok.tython.proto.AbstractExpr.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = guard_.toBuilder();
            }
            guard_ = input.readMessage(com.giyeok.tython.proto.AbstractExpr.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(guard_);
              guard_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              body_ = new java.util.ArrayList<com.giyeok.tython.proto.AbstractStmt>();
              mutable_bitField0_ |= 0x00000002;
            }
            body_.add(
                input.readMessage(com.giyeok.tython.proto.AbstractStmt.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        body_ = java.util.Collections.unmodifiableList(body_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_MatchCase_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_MatchCase_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.giyeok.tython.proto.MatchCase.class, com.giyeok.tython.proto.MatchCase.Builder.class);
  }

  private int bitField0_;
  public static final int PATTERN_FIELD_NUMBER = 1;
  private com.giyeok.tython.proto.AbstractPattern pattern_;
  /**
   * <code>.com.giyeok.tython.proto.AbstractPattern pattern = 1;</code>
   * @return Whether the pattern field is set.
   */
  @java.lang.Override
  public boolean hasPattern() {
    return pattern_ != null;
  }
  /**
   * <code>.com.giyeok.tython.proto.AbstractPattern pattern = 1;</code>
   * @return The pattern.
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractPattern getPattern() {
    return pattern_ == null ? com.giyeok.tython.proto.AbstractPattern.getDefaultInstance() : pattern_;
  }
  /**
   * <code>.com.giyeok.tython.proto.AbstractPattern pattern = 1;</code>
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractPatternOrBuilder getPatternOrBuilder() {
    return getPattern();
  }

  public static final int GUARD_FIELD_NUMBER = 2;
  private com.giyeok.tython.proto.AbstractExpr guard_;
  /**
   * <code>optional .com.giyeok.tython.proto.AbstractExpr guard = 2;</code>
   * @return Whether the guard field is set.
   */
  @java.lang.Override
  public boolean hasGuard() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .com.giyeok.tython.proto.AbstractExpr guard = 2;</code>
   * @return The guard.
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractExpr getGuard() {
    return guard_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : guard_;
  }
  /**
   * <code>optional .com.giyeok.tython.proto.AbstractExpr guard = 2;</code>
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractExprOrBuilder getGuardOrBuilder() {
    return guard_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : guard_;
  }

  public static final int BODY_FIELD_NUMBER = 3;
  private java.util.List<com.giyeok.tython.proto.AbstractStmt> body_;
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.giyeok.tython.proto.AbstractStmt> getBodyList() {
    return body_;
  }
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.giyeok.tython.proto.AbstractStmtOrBuilder> 
      getBodyOrBuilderList() {
    return body_;
  }
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 3;</code>
   */
  @java.lang.Override
  public int getBodyCount() {
    return body_.size();
  }
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 3;</code>
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractStmt getBody(int index) {
    return body_.get(index);
  }
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 3;</code>
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractStmtOrBuilder getBodyOrBuilder(
      int index) {
    return body_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (pattern_ != null) {
      output.writeMessage(1, getPattern());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getGuard());
    }
    for (int i = 0; i < body_.size(); i++) {
      output.writeMessage(3, body_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (pattern_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPattern());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getGuard());
    }
    for (int i = 0; i < body_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, body_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.giyeok.tython.proto.MatchCase)) {
      return super.equals(obj);
    }
    com.giyeok.tython.proto.MatchCase other = (com.giyeok.tython.proto.MatchCase) obj;

    if (hasPattern() != other.hasPattern()) return false;
    if (hasPattern()) {
      if (!getPattern()
          .equals(other.getPattern())) return false;
    }
    if (hasGuard() != other.hasGuard()) return false;
    if (hasGuard()) {
      if (!getGuard()
          .equals(other.getGuard())) return false;
    }
    if (!getBodyList()
        .equals(other.getBodyList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPattern()) {
      hash = (37 * hash) + PATTERN_FIELD_NUMBER;
      hash = (53 * hash) + getPattern().hashCode();
    }
    if (hasGuard()) {
      hash = (37 * hash) + GUARD_FIELD_NUMBER;
      hash = (53 * hash) + getGuard().hashCode();
    }
    if (getBodyCount() > 0) {
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBodyList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.giyeok.tython.proto.MatchCase parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.giyeok.tython.proto.MatchCase parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.giyeok.tython.proto.MatchCase parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.giyeok.tython.proto.MatchCase parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.giyeok.tython.proto.MatchCase parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.giyeok.tython.proto.MatchCase parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.giyeok.tython.proto.MatchCase parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.giyeok.tython.proto.MatchCase parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.giyeok.tython.proto.MatchCase parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.giyeok.tython.proto.MatchCase parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.giyeok.tython.proto.MatchCase parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.giyeok.tython.proto.MatchCase parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.giyeok.tython.proto.MatchCase prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.giyeok.tython.proto.MatchCase}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.giyeok.tython.proto.MatchCase)
      com.giyeok.tython.proto.MatchCaseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_MatchCase_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_MatchCase_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.giyeok.tython.proto.MatchCase.class, com.giyeok.tython.proto.MatchCase.Builder.class);
    }

    // Construct using com.giyeok.tython.proto.MatchCase.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getGuardFieldBuilder();
        getBodyFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (patternBuilder_ == null) {
        pattern_ = null;
      } else {
        pattern_ = null;
        patternBuilder_ = null;
      }
      if (guardBuilder_ == null) {
        guard_ = null;
      } else {
        guardBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (bodyBuilder_ == null) {
        body_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        bodyBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_MatchCase_descriptor;
    }

    @java.lang.Override
    public com.giyeok.tython.proto.MatchCase getDefaultInstanceForType() {
      return com.giyeok.tython.proto.MatchCase.getDefaultInstance();
    }

    @java.lang.Override
    public com.giyeok.tython.proto.MatchCase build() {
      com.giyeok.tython.proto.MatchCase result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.giyeok.tython.proto.MatchCase buildPartial() {
      com.giyeok.tython.proto.MatchCase result = new com.giyeok.tython.proto.MatchCase(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (patternBuilder_ == null) {
        result.pattern_ = pattern_;
      } else {
        result.pattern_ = patternBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (guardBuilder_ == null) {
          result.guard_ = guard_;
        } else {
          result.guard_ = guardBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      if (bodyBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          body_ = java.util.Collections.unmodifiableList(body_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.body_ = body_;
      } else {
        result.body_ = bodyBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.giyeok.tython.proto.MatchCase) {
        return mergeFrom((com.giyeok.tython.proto.MatchCase)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.giyeok.tython.proto.MatchCase other) {
      if (other == com.giyeok.tython.proto.MatchCase.getDefaultInstance()) return this;
      if (other.hasPattern()) {
        mergePattern(other.getPattern());
      }
      if (other.hasGuard()) {
        mergeGuard(other.getGuard());
      }
      if (bodyBuilder_ == null) {
        if (!other.body_.isEmpty()) {
          if (body_.isEmpty()) {
            body_ = other.body_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureBodyIsMutable();
            body_.addAll(other.body_);
          }
          onChanged();
        }
      } else {
        if (!other.body_.isEmpty()) {
          if (bodyBuilder_.isEmpty()) {
            bodyBuilder_.dispose();
            bodyBuilder_ = null;
            body_ = other.body_;
            bitField0_ = (bitField0_ & ~0x00000002);
            bodyBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBodyFieldBuilder() : null;
          } else {
            bodyBuilder_.addAllMessages(other.body_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.giyeok.tython.proto.MatchCase parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.giyeok.tython.proto.MatchCase) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.giyeok.tython.proto.AbstractPattern pattern_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractPattern, com.giyeok.tython.proto.AbstractPattern.Builder, com.giyeok.tython.proto.AbstractPatternOrBuilder> patternBuilder_;
    /**
     * <code>.com.giyeok.tython.proto.AbstractPattern pattern = 1;</code>
     * @return Whether the pattern field is set.
     */
    public boolean hasPattern() {
      return patternBuilder_ != null || pattern_ != null;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractPattern pattern = 1;</code>
     * @return The pattern.
     */
    public com.giyeok.tython.proto.AbstractPattern getPattern() {
      if (patternBuilder_ == null) {
        return pattern_ == null ? com.giyeok.tython.proto.AbstractPattern.getDefaultInstance() : pattern_;
      } else {
        return patternBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractPattern pattern = 1;</code>
     */
    public Builder setPattern(com.giyeok.tython.proto.AbstractPattern value) {
      if (patternBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pattern_ = value;
        onChanged();
      } else {
        patternBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractPattern pattern = 1;</code>
     */
    public Builder setPattern(
        com.giyeok.tython.proto.AbstractPattern.Builder builderForValue) {
      if (patternBuilder_ == null) {
        pattern_ = builderForValue.build();
        onChanged();
      } else {
        patternBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractPattern pattern = 1;</code>
     */
    public Builder mergePattern(com.giyeok.tython.proto.AbstractPattern value) {
      if (patternBuilder_ == null) {
        if (pattern_ != null) {
          pattern_ =
            com.giyeok.tython.proto.AbstractPattern.newBuilder(pattern_).mergeFrom(value).buildPartial();
        } else {
          pattern_ = value;
        }
        onChanged();
      } else {
        patternBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractPattern pattern = 1;</code>
     */
    public Builder clearPattern() {
      if (patternBuilder_ == null) {
        pattern_ = null;
        onChanged();
      } else {
        pattern_ = null;
        patternBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractPattern pattern = 1;</code>
     */
    public com.giyeok.tython.proto.AbstractPattern.Builder getPatternBuilder() {
      
      onChanged();
      return getPatternFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractPattern pattern = 1;</code>
     */
    public com.giyeok.tython.proto.AbstractPatternOrBuilder getPatternOrBuilder() {
      if (patternBuilder_ != null) {
        return patternBuilder_.getMessageOrBuilder();
      } else {
        return pattern_ == null ?
            com.giyeok.tython.proto.AbstractPattern.getDefaultInstance() : pattern_;
      }
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractPattern pattern = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractPattern, com.giyeok.tython.proto.AbstractPattern.Builder, com.giyeok.tython.proto.AbstractPatternOrBuilder> 
        getPatternFieldBuilder() {
      if (patternBuilder_ == null) {
        patternBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.giyeok.tython.proto.AbstractPattern, com.giyeok.tython.proto.AbstractPattern.Builder, com.giyeok.tython.proto.AbstractPatternOrBuilder>(
                getPattern(),
                getParentForChildren(),
                isClean());
        pattern_ = null;
      }
      return patternBuilder_;
    }

    private com.giyeok.tython.proto.AbstractExpr guard_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder> guardBuilder_;
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr guard = 2;</code>
     * @return Whether the guard field is set.
     */
    public boolean hasGuard() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr guard = 2;</code>
     * @return The guard.
     */
    public com.giyeok.tython.proto.AbstractExpr getGuard() {
      if (guardBuilder_ == null) {
        return guard_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : guard_;
      } else {
        return guardBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr guard = 2;</code>
     */
    public Builder setGuard(com.giyeok.tython.proto.AbstractExpr value) {
      if (guardBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        guard_ = value;
        onChanged();
      } else {
        guardBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr guard = 2;</code>
     */
    public Builder setGuard(
        com.giyeok.tython.proto.AbstractExpr.Builder builderForValue) {
      if (guardBuilder_ == null) {
        guard_ = builderForValue.build();
        onChanged();
      } else {
        guardBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr guard = 2;</code>
     */
    public Builder mergeGuard(com.giyeok.tython.proto.AbstractExpr value) {
      if (guardBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            guard_ != null &&
            guard_ != com.giyeok.tython.proto.AbstractExpr.getDefaultInstance()) {
          guard_ =
            com.giyeok.tython.proto.AbstractExpr.newBuilder(guard_).mergeFrom(value).buildPartial();
        } else {
          guard_ = value;
        }
        onChanged();
      } else {
        guardBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr guard = 2;</code>
     */
    public Builder clearGuard() {
      if (guardBuilder_ == null) {
        guard_ = null;
        onChanged();
      } else {
        guardBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr guard = 2;</code>
     */
    public com.giyeok.tython.proto.AbstractExpr.Builder getGuardBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getGuardFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr guard = 2;</code>
     */
    public com.giyeok.tython.proto.AbstractExprOrBuilder getGuardOrBuilder() {
      if (guardBuilder_ != null) {
        return guardBuilder_.getMessageOrBuilder();
      } else {
        return guard_ == null ?
            com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : guard_;
      }
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr guard = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder> 
        getGuardFieldBuilder() {
      if (guardBuilder_ == null) {
        guardBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder>(
                getGuard(),
                getParentForChildren(),
                isClean());
        guard_ = null;
      }
      return guardBuilder_;
    }

    private java.util.List<com.giyeok.tython.proto.AbstractStmt> body_ =
      java.util.Collections.emptyList();
    private void ensureBodyIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        body_ = new java.util.ArrayList<com.giyeok.tython.proto.AbstractStmt>(body_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.giyeok.tython.proto.AbstractStmt, com.giyeok.tython.proto.AbstractStmt.Builder, com.giyeok.tython.proto.AbstractStmtOrBuilder> bodyBuilder_;

    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 3;</code>
     */
    public java.util.List<com.giyeok.tython.proto.AbstractStmt> getBodyList() {
      if (bodyBuilder_ == null) {
        return java.util.Collections.unmodifiableList(body_);
      } else {
        return bodyBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 3;</code>
     */
    public int getBodyCount() {
      if (bodyBuilder_ == null) {
        return body_.size();
      } else {
        return bodyBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 3;</code>
     */
    public com.giyeok.tython.proto.AbstractStmt getBody(int index) {
      if (bodyBuilder_ == null) {
        return body_.get(index);
      } else {
        return bodyBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 3;</code>
     */
    public Builder setBody(
        int index, com.giyeok.tython.proto.AbstractStmt value) {
      if (bodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBodyIsMutable();
        body_.set(index, value);
        onChanged();
      } else {
        bodyBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 3;</code>
     */
    public Builder setBody(
        int index, com.giyeok.tython.proto.AbstractStmt.Builder builderForValue) {
      if (bodyBuilder_ == null) {
        ensureBodyIsMutable();
        body_.set(index, builderForValue.build());
        onChanged();
      } else {
        bodyBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 3;</code>
     */
    public Builder addBody(com.giyeok.tython.proto.AbstractStmt value) {
      if (bodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBodyIsMutable();
        body_.add(value);
        onChanged();
      } else {
        bodyBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 3;</code>
     */
    public Builder addBody(
        int index, com.giyeok.tython.proto.AbstractStmt value) {
      if (bodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBodyIsMutable();
        body_.add(index, value);
        onChanged();
      } else {
        bodyBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 3;</code>
     */
    public Builder addBody(
        com.giyeok.tython.proto.AbstractStmt.Builder builderForValue) {
      if (bodyBuilder_ == null) {
        ensureBodyIsMutable();
        body_.add(builderForValue.build());
        onChanged();
      } else {
        bodyBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 3;</code>
     */
    public Builder addBody(
        int index, com.giyeok.tython.proto.AbstractStmt.Builder builderForValue) {
      if (bodyBuilder_ == null) {
        ensureBodyIsMutable();
        body_.add(index, builderForValue.build());
        onChanged();
      } else {
        bodyBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 3;</code>
     */
    public Builder addAllBody(
        java.lang.Iterable<? extends com.giyeok.tython.proto.AbstractStmt> values) {
      if (bodyBuilder_ == null) {
        ensureBodyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, body_);
        onChanged();
      } else {
        bodyBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 3;</code>
     */
    public Builder clearBody() {
      if (bodyBuilder_ == null) {
        body_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        bodyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 3;</code>
     */
    public Builder removeBody(int index) {
      if (bodyBuilder_ == null) {
        ensureBodyIsMutable();
        body_.remove(index);
        onChanged();
      } else {
        bodyBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 3;</code>
     */
    public com.giyeok.tython.proto.AbstractStmt.Builder getBodyBuilder(
        int index) {
      return getBodyFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 3;</code>
     */
    public com.giyeok.tython.proto.AbstractStmtOrBuilder getBodyOrBuilder(
        int index) {
      if (bodyBuilder_ == null) {
        return body_.get(index);  } else {
        return bodyBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 3;</code>
     */
    public java.util.List<? extends com.giyeok.tython.proto.AbstractStmtOrBuilder> 
         getBodyOrBuilderList() {
      if (bodyBuilder_ != null) {
        return bodyBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(body_);
      }
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 3;</code>
     */
    public com.giyeok.tython.proto.AbstractStmt.Builder addBodyBuilder() {
      return getBodyFieldBuilder().addBuilder(
          com.giyeok.tython.proto.AbstractStmt.getDefaultInstance());
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 3;</code>
     */
    public com.giyeok.tython.proto.AbstractStmt.Builder addBodyBuilder(
        int index) {
      return getBodyFieldBuilder().addBuilder(
          index, com.giyeok.tython.proto.AbstractStmt.getDefaultInstance());
    }
    /**
     * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 3;</code>
     */
    public java.util.List<com.giyeok.tython.proto.AbstractStmt.Builder> 
         getBodyBuilderList() {
      return getBodyFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.giyeok.tython.proto.AbstractStmt, com.giyeok.tython.proto.AbstractStmt.Builder, com.giyeok.tython.proto.AbstractStmtOrBuilder> 
        getBodyFieldBuilder() {
      if (bodyBuilder_ == null) {
        bodyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.giyeok.tython.proto.AbstractStmt, com.giyeok.tython.proto.AbstractStmt.Builder, com.giyeok.tython.proto.AbstractStmtOrBuilder>(
                body_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      return bodyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.giyeok.tython.proto.MatchCase)
  }

  // @@protoc_insertion_point(class_scope:com.giyeok.tython.proto.MatchCase)
  private static final com.giyeok.tython.proto.MatchCase DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.giyeok.tython.proto.MatchCase();
  }

  public static com.giyeok.tython.proto.MatchCase getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MatchCase>
      PARSER = new com.google.protobuf.AbstractParser<MatchCase>() {
    @java.lang.Override
    public MatchCase parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MatchCase(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MatchCase> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MatchCase> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.giyeok.tython.proto.MatchCase getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

