// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: python3_10.proto

package com.giyeok.tython.proto;

/**
 * Protobuf type {@code com.giyeok.tython.proto.Slice}
 */
public final class Slice extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.giyeok.tython.proto.Slice)
    SliceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Slice.newBuilder() to construct.
  private Slice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Slice() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Slice();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Slice(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.giyeok.tython.proto.AbstractExpr.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = lower_.toBuilder();
            }
            lower_ = input.readMessage(com.giyeok.tython.proto.AbstractExpr.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lower_);
              lower_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            com.giyeok.tython.proto.AbstractExpr.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) != 0)) {
              subBuilder = upper_.toBuilder();
            }
            upper_ = input.readMessage(com.giyeok.tython.proto.AbstractExpr.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(upper_);
              upper_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          case 26: {
            com.giyeok.tython.proto.AbstractExpr.Builder subBuilder = null;
            if (((bitField0_ & 0x00000004) != 0)) {
              subBuilder = step_.toBuilder();
            }
            step_ = input.readMessage(com.giyeok.tython.proto.AbstractExpr.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(step_);
              step_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000004;
            break;
          }
          case 32: {

            lineno_ = input.readInt32();
            break;
          }
          case 40: {

            colOffset_ = input.readInt32();
            break;
          }
          case 48: {
            bitField0_ |= 0x00000008;
            endLineno_ = input.readInt32();
            break;
          }
          case 56: {
            bitField0_ |= 0x00000010;
            endColOffset_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_Slice_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_Slice_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.giyeok.tython.proto.Slice.class, com.giyeok.tython.proto.Slice.Builder.class);
  }

  private int bitField0_;
  public static final int LOWER_FIELD_NUMBER = 1;
  private com.giyeok.tython.proto.AbstractExpr lower_;
  /**
   * <code>optional .com.giyeok.tython.proto.AbstractExpr lower = 1;</code>
   * @return Whether the lower field is set.
   */
  @java.lang.Override
  public boolean hasLower() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .com.giyeok.tython.proto.AbstractExpr lower = 1;</code>
   * @return The lower.
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractExpr getLower() {
    return lower_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : lower_;
  }
  /**
   * <code>optional .com.giyeok.tython.proto.AbstractExpr lower = 1;</code>
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractExprOrBuilder getLowerOrBuilder() {
    return lower_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : lower_;
  }

  public static final int UPPER_FIELD_NUMBER = 2;
  private com.giyeok.tython.proto.AbstractExpr upper_;
  /**
   * <code>optional .com.giyeok.tython.proto.AbstractExpr upper = 2;</code>
   * @return Whether the upper field is set.
   */
  @java.lang.Override
  public boolean hasUpper() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .com.giyeok.tython.proto.AbstractExpr upper = 2;</code>
   * @return The upper.
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractExpr getUpper() {
    return upper_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : upper_;
  }
  /**
   * <code>optional .com.giyeok.tython.proto.AbstractExpr upper = 2;</code>
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractExprOrBuilder getUpperOrBuilder() {
    return upper_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : upper_;
  }

  public static final int STEP_FIELD_NUMBER = 3;
  private com.giyeok.tython.proto.AbstractExpr step_;
  /**
   * <code>optional .com.giyeok.tython.proto.AbstractExpr step = 3;</code>
   * @return Whether the step field is set.
   */
  @java.lang.Override
  public boolean hasStep() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .com.giyeok.tython.proto.AbstractExpr step = 3;</code>
   * @return The step.
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractExpr getStep() {
    return step_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : step_;
  }
  /**
   * <code>optional .com.giyeok.tython.proto.AbstractExpr step = 3;</code>
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractExprOrBuilder getStepOrBuilder() {
    return step_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : step_;
  }

  public static final int LINENO_FIELD_NUMBER = 4;
  private int lineno_;
  /**
   * <code>int32 lineno = 4;</code>
   * @return The lineno.
   */
  @java.lang.Override
  public int getLineno() {
    return lineno_;
  }

  public static final int COL_OFFSET_FIELD_NUMBER = 5;
  private int colOffset_;
  /**
   * <code>int32 col_offset = 5;</code>
   * @return The colOffset.
   */
  @java.lang.Override
  public int getColOffset() {
    return colOffset_;
  }

  public static final int END_LINENO_FIELD_NUMBER = 6;
  private int endLineno_;
  /**
   * <code>optional int32 end_lineno = 6;</code>
   * @return Whether the endLineno field is set.
   */
  @java.lang.Override
  public boolean hasEndLineno() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional int32 end_lineno = 6;</code>
   * @return The endLineno.
   */
  @java.lang.Override
  public int getEndLineno() {
    return endLineno_;
  }

  public static final int END_COL_OFFSET_FIELD_NUMBER = 7;
  private int endColOffset_;
  /**
   * <code>optional int32 end_col_offset = 7;</code>
   * @return Whether the endColOffset field is set.
   */
  @java.lang.Override
  public boolean hasEndColOffset() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional int32 end_col_offset = 7;</code>
   * @return The endColOffset.
   */
  @java.lang.Override
  public int getEndColOffset() {
    return endColOffset_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getLower());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getUpper());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getStep());
    }
    if (lineno_ != 0) {
      output.writeInt32(4, lineno_);
    }
    if (colOffset_ != 0) {
      output.writeInt32(5, colOffset_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt32(6, endLineno_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt32(7, endColOffset_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLower());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUpper());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getStep());
    }
    if (lineno_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, lineno_);
    }
    if (colOffset_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, colOffset_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, endLineno_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, endColOffset_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.giyeok.tython.proto.Slice)) {
      return super.equals(obj);
    }
    com.giyeok.tython.proto.Slice other = (com.giyeok.tython.proto.Slice) obj;

    if (hasLower() != other.hasLower()) return false;
    if (hasLower()) {
      if (!getLower()
          .equals(other.getLower())) return false;
    }
    if (hasUpper() != other.hasUpper()) return false;
    if (hasUpper()) {
      if (!getUpper()
          .equals(other.getUpper())) return false;
    }
    if (hasStep() != other.hasStep()) return false;
    if (hasStep()) {
      if (!getStep()
          .equals(other.getStep())) return false;
    }
    if (getLineno()
        != other.getLineno()) return false;
    if (getColOffset()
        != other.getColOffset()) return false;
    if (hasEndLineno() != other.hasEndLineno()) return false;
    if (hasEndLineno()) {
      if (getEndLineno()
          != other.getEndLineno()) return false;
    }
    if (hasEndColOffset() != other.hasEndColOffset()) return false;
    if (hasEndColOffset()) {
      if (getEndColOffset()
          != other.getEndColOffset()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLower()) {
      hash = (37 * hash) + LOWER_FIELD_NUMBER;
      hash = (53 * hash) + getLower().hashCode();
    }
    if (hasUpper()) {
      hash = (37 * hash) + UPPER_FIELD_NUMBER;
      hash = (53 * hash) + getUpper().hashCode();
    }
    if (hasStep()) {
      hash = (37 * hash) + STEP_FIELD_NUMBER;
      hash = (53 * hash) + getStep().hashCode();
    }
    hash = (37 * hash) + LINENO_FIELD_NUMBER;
    hash = (53 * hash) + getLineno();
    hash = (37 * hash) + COL_OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + getColOffset();
    if (hasEndLineno()) {
      hash = (37 * hash) + END_LINENO_FIELD_NUMBER;
      hash = (53 * hash) + getEndLineno();
    }
    if (hasEndColOffset()) {
      hash = (37 * hash) + END_COL_OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + getEndColOffset();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.giyeok.tython.proto.Slice parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.giyeok.tython.proto.Slice parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.giyeok.tython.proto.Slice parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.giyeok.tython.proto.Slice parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.giyeok.tython.proto.Slice parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.giyeok.tython.proto.Slice parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.giyeok.tython.proto.Slice parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.giyeok.tython.proto.Slice parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.giyeok.tython.proto.Slice parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.giyeok.tython.proto.Slice parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.giyeok.tython.proto.Slice parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.giyeok.tython.proto.Slice parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.giyeok.tython.proto.Slice prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.giyeok.tython.proto.Slice}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.giyeok.tython.proto.Slice)
      com.giyeok.tython.proto.SliceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_Slice_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_Slice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.giyeok.tython.proto.Slice.class, com.giyeok.tython.proto.Slice.Builder.class);
    }

    // Construct using com.giyeok.tython.proto.Slice.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getLowerFieldBuilder();
        getUpperFieldBuilder();
        getStepFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (lowerBuilder_ == null) {
        lower_ = null;
      } else {
        lowerBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (upperBuilder_ == null) {
        upper_ = null;
      } else {
        upperBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (stepBuilder_ == null) {
        step_ = null;
      } else {
        stepBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      lineno_ = 0;

      colOffset_ = 0;

      endLineno_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      endColOffset_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_Slice_descriptor;
    }

    @java.lang.Override
    public com.giyeok.tython.proto.Slice getDefaultInstanceForType() {
      return com.giyeok.tython.proto.Slice.getDefaultInstance();
    }

    @java.lang.Override
    public com.giyeok.tython.proto.Slice build() {
      com.giyeok.tython.proto.Slice result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.giyeok.tython.proto.Slice buildPartial() {
      com.giyeok.tython.proto.Slice result = new com.giyeok.tython.proto.Slice(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (lowerBuilder_ == null) {
          result.lower_ = lower_;
        } else {
          result.lower_ = lowerBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        if (upperBuilder_ == null) {
          result.upper_ = upper_;
        } else {
          result.upper_ = upperBuilder_.build();
        }
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        if (stepBuilder_ == null) {
          result.step_ = step_;
        } else {
          result.step_ = stepBuilder_.build();
        }
        to_bitField0_ |= 0x00000004;
      }
      result.lineno_ = lineno_;
      result.colOffset_ = colOffset_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.endLineno_ = endLineno_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.endColOffset_ = endColOffset_;
        to_bitField0_ |= 0x00000010;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.giyeok.tython.proto.Slice) {
        return mergeFrom((com.giyeok.tython.proto.Slice)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.giyeok.tython.proto.Slice other) {
      if (other == com.giyeok.tython.proto.Slice.getDefaultInstance()) return this;
      if (other.hasLower()) {
        mergeLower(other.getLower());
      }
      if (other.hasUpper()) {
        mergeUpper(other.getUpper());
      }
      if (other.hasStep()) {
        mergeStep(other.getStep());
      }
      if (other.getLineno() != 0) {
        setLineno(other.getLineno());
      }
      if (other.getColOffset() != 0) {
        setColOffset(other.getColOffset());
      }
      if (other.hasEndLineno()) {
        setEndLineno(other.getEndLineno());
      }
      if (other.hasEndColOffset()) {
        setEndColOffset(other.getEndColOffset());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.giyeok.tython.proto.Slice parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.giyeok.tython.proto.Slice) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.giyeok.tython.proto.AbstractExpr lower_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder> lowerBuilder_;
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr lower = 1;</code>
     * @return Whether the lower field is set.
     */
    public boolean hasLower() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr lower = 1;</code>
     * @return The lower.
     */
    public com.giyeok.tython.proto.AbstractExpr getLower() {
      if (lowerBuilder_ == null) {
        return lower_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : lower_;
      } else {
        return lowerBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr lower = 1;</code>
     */
    public Builder setLower(com.giyeok.tython.proto.AbstractExpr value) {
      if (lowerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lower_ = value;
        onChanged();
      } else {
        lowerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr lower = 1;</code>
     */
    public Builder setLower(
        com.giyeok.tython.proto.AbstractExpr.Builder builderForValue) {
      if (lowerBuilder_ == null) {
        lower_ = builderForValue.build();
        onChanged();
      } else {
        lowerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr lower = 1;</code>
     */
    public Builder mergeLower(com.giyeok.tython.proto.AbstractExpr value) {
      if (lowerBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            lower_ != null &&
            lower_ != com.giyeok.tython.proto.AbstractExpr.getDefaultInstance()) {
          lower_ =
            com.giyeok.tython.proto.AbstractExpr.newBuilder(lower_).mergeFrom(value).buildPartial();
        } else {
          lower_ = value;
        }
        onChanged();
      } else {
        lowerBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr lower = 1;</code>
     */
    public Builder clearLower() {
      if (lowerBuilder_ == null) {
        lower_ = null;
        onChanged();
      } else {
        lowerBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr lower = 1;</code>
     */
    public com.giyeok.tython.proto.AbstractExpr.Builder getLowerBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getLowerFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr lower = 1;</code>
     */
    public com.giyeok.tython.proto.AbstractExprOrBuilder getLowerOrBuilder() {
      if (lowerBuilder_ != null) {
        return lowerBuilder_.getMessageOrBuilder();
      } else {
        return lower_ == null ?
            com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : lower_;
      }
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr lower = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder> 
        getLowerFieldBuilder() {
      if (lowerBuilder_ == null) {
        lowerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder>(
                getLower(),
                getParentForChildren(),
                isClean());
        lower_ = null;
      }
      return lowerBuilder_;
    }

    private com.giyeok.tython.proto.AbstractExpr upper_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder> upperBuilder_;
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr upper = 2;</code>
     * @return Whether the upper field is set.
     */
    public boolean hasUpper() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr upper = 2;</code>
     * @return The upper.
     */
    public com.giyeok.tython.proto.AbstractExpr getUpper() {
      if (upperBuilder_ == null) {
        return upper_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : upper_;
      } else {
        return upperBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr upper = 2;</code>
     */
    public Builder setUpper(com.giyeok.tython.proto.AbstractExpr value) {
      if (upperBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        upper_ = value;
        onChanged();
      } else {
        upperBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr upper = 2;</code>
     */
    public Builder setUpper(
        com.giyeok.tython.proto.AbstractExpr.Builder builderForValue) {
      if (upperBuilder_ == null) {
        upper_ = builderForValue.build();
        onChanged();
      } else {
        upperBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr upper = 2;</code>
     */
    public Builder mergeUpper(com.giyeok.tython.proto.AbstractExpr value) {
      if (upperBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
            upper_ != null &&
            upper_ != com.giyeok.tython.proto.AbstractExpr.getDefaultInstance()) {
          upper_ =
            com.giyeok.tython.proto.AbstractExpr.newBuilder(upper_).mergeFrom(value).buildPartial();
        } else {
          upper_ = value;
        }
        onChanged();
      } else {
        upperBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr upper = 2;</code>
     */
    public Builder clearUpper() {
      if (upperBuilder_ == null) {
        upper_ = null;
        onChanged();
      } else {
        upperBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr upper = 2;</code>
     */
    public com.giyeok.tython.proto.AbstractExpr.Builder getUpperBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getUpperFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr upper = 2;</code>
     */
    public com.giyeok.tython.proto.AbstractExprOrBuilder getUpperOrBuilder() {
      if (upperBuilder_ != null) {
        return upperBuilder_.getMessageOrBuilder();
      } else {
        return upper_ == null ?
            com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : upper_;
      }
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr upper = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder> 
        getUpperFieldBuilder() {
      if (upperBuilder_ == null) {
        upperBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder>(
                getUpper(),
                getParentForChildren(),
                isClean());
        upper_ = null;
      }
      return upperBuilder_;
    }

    private com.giyeok.tython.proto.AbstractExpr step_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder> stepBuilder_;
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr step = 3;</code>
     * @return Whether the step field is set.
     */
    public boolean hasStep() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr step = 3;</code>
     * @return The step.
     */
    public com.giyeok.tython.proto.AbstractExpr getStep() {
      if (stepBuilder_ == null) {
        return step_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : step_;
      } else {
        return stepBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr step = 3;</code>
     */
    public Builder setStep(com.giyeok.tython.proto.AbstractExpr value) {
      if (stepBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        step_ = value;
        onChanged();
      } else {
        stepBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr step = 3;</code>
     */
    public Builder setStep(
        com.giyeok.tython.proto.AbstractExpr.Builder builderForValue) {
      if (stepBuilder_ == null) {
        step_ = builderForValue.build();
        onChanged();
      } else {
        stepBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr step = 3;</code>
     */
    public Builder mergeStep(com.giyeok.tython.proto.AbstractExpr value) {
      if (stepBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
            step_ != null &&
            step_ != com.giyeok.tython.proto.AbstractExpr.getDefaultInstance()) {
          step_ =
            com.giyeok.tython.proto.AbstractExpr.newBuilder(step_).mergeFrom(value).buildPartial();
        } else {
          step_ = value;
        }
        onChanged();
      } else {
        stepBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr step = 3;</code>
     */
    public Builder clearStep() {
      if (stepBuilder_ == null) {
        step_ = null;
        onChanged();
      } else {
        stepBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr step = 3;</code>
     */
    public com.giyeok.tython.proto.AbstractExpr.Builder getStepBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getStepFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr step = 3;</code>
     */
    public com.giyeok.tython.proto.AbstractExprOrBuilder getStepOrBuilder() {
      if (stepBuilder_ != null) {
        return stepBuilder_.getMessageOrBuilder();
      } else {
        return step_ == null ?
            com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : step_;
      }
    }
    /**
     * <code>optional .com.giyeok.tython.proto.AbstractExpr step = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder> 
        getStepFieldBuilder() {
      if (stepBuilder_ == null) {
        stepBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder>(
                getStep(),
                getParentForChildren(),
                isClean());
        step_ = null;
      }
      return stepBuilder_;
    }

    private int lineno_ ;
    /**
     * <code>int32 lineno = 4;</code>
     * @return The lineno.
     */
    @java.lang.Override
    public int getLineno() {
      return lineno_;
    }
    /**
     * <code>int32 lineno = 4;</code>
     * @param value The lineno to set.
     * @return This builder for chaining.
     */
    public Builder setLineno(int value) {
      
      lineno_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 lineno = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLineno() {
      
      lineno_ = 0;
      onChanged();
      return this;
    }

    private int colOffset_ ;
    /**
     * <code>int32 col_offset = 5;</code>
     * @return The colOffset.
     */
    @java.lang.Override
    public int getColOffset() {
      return colOffset_;
    }
    /**
     * <code>int32 col_offset = 5;</code>
     * @param value The colOffset to set.
     * @return This builder for chaining.
     */
    public Builder setColOffset(int value) {
      
      colOffset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 col_offset = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearColOffset() {
      
      colOffset_ = 0;
      onChanged();
      return this;
    }

    private int endLineno_ ;
    /**
     * <code>optional int32 end_lineno = 6;</code>
     * @return Whether the endLineno field is set.
     */
    @java.lang.Override
    public boolean hasEndLineno() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 end_lineno = 6;</code>
     * @return The endLineno.
     */
    @java.lang.Override
    public int getEndLineno() {
      return endLineno_;
    }
    /**
     * <code>optional int32 end_lineno = 6;</code>
     * @param value The endLineno to set.
     * @return This builder for chaining.
     */
    public Builder setEndLineno(int value) {
      bitField0_ |= 0x00000008;
      endLineno_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 end_lineno = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndLineno() {
      bitField0_ = (bitField0_ & ~0x00000008);
      endLineno_ = 0;
      onChanged();
      return this;
    }

    private int endColOffset_ ;
    /**
     * <code>optional int32 end_col_offset = 7;</code>
     * @return Whether the endColOffset field is set.
     */
    @java.lang.Override
    public boolean hasEndColOffset() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 end_col_offset = 7;</code>
     * @return The endColOffset.
     */
    @java.lang.Override
    public int getEndColOffset() {
      return endColOffset_;
    }
    /**
     * <code>optional int32 end_col_offset = 7;</code>
     * @param value The endColOffset to set.
     * @return This builder for chaining.
     */
    public Builder setEndColOffset(int value) {
      bitField0_ |= 0x00000010;
      endColOffset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 end_col_offset = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndColOffset() {
      bitField0_ = (bitField0_ & ~0x00000010);
      endColOffset_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.giyeok.tython.proto.Slice)
  }

  // @@protoc_insertion_point(class_scope:com.giyeok.tython.proto.Slice)
  private static final com.giyeok.tython.proto.Slice DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.giyeok.tython.proto.Slice();
  }

  public static com.giyeok.tython.proto.Slice getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Slice>
      PARSER = new com.google.protobuf.AbstractParser<Slice>() {
    @java.lang.Override
    public Slice parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Slice(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Slice> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Slice> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.giyeok.tython.proto.Slice getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

