// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: python3_10.proto

package com.giyeok.tython.proto;

/**
 * Protobuf type {@code com.giyeok.tython.proto.UnaryOp}
 */
public final class UnaryOp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.giyeok.tython.proto.UnaryOp)
    UnaryOpOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UnaryOp.newBuilder() to construct.
  private UnaryOp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UnaryOp() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UnaryOp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UnaryOp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.giyeok.tython.proto.AbstractUnaryop.Builder subBuilder = null;
            if (op_ != null) {
              subBuilder = op_.toBuilder();
            }
            op_ = input.readMessage(com.giyeok.tython.proto.AbstractUnaryop.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(op_);
              op_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.giyeok.tython.proto.AbstractExpr.Builder subBuilder = null;
            if (operand_ != null) {
              subBuilder = operand_.toBuilder();
            }
            operand_ = input.readMessage(com.giyeok.tython.proto.AbstractExpr.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(operand_);
              operand_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {

            lineno_ = input.readInt32();
            break;
          }
          case 32: {

            colOffset_ = input.readInt32();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000001;
            endLineno_ = input.readInt32();
            break;
          }
          case 48: {
            bitField0_ |= 0x00000002;
            endColOffset_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_UnaryOp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_UnaryOp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.giyeok.tython.proto.UnaryOp.class, com.giyeok.tython.proto.UnaryOp.Builder.class);
  }

  private int bitField0_;
  public static final int OP_FIELD_NUMBER = 1;
  private com.giyeok.tython.proto.AbstractUnaryop op_;
  /**
   * <code>.com.giyeok.tython.proto.AbstractUnaryop op = 1;</code>
   * @return Whether the op field is set.
   */
  @java.lang.Override
  public boolean hasOp() {
    return op_ != null;
  }
  /**
   * <code>.com.giyeok.tython.proto.AbstractUnaryop op = 1;</code>
   * @return The op.
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractUnaryop getOp() {
    return op_ == null ? com.giyeok.tython.proto.AbstractUnaryop.getDefaultInstance() : op_;
  }
  /**
   * <code>.com.giyeok.tython.proto.AbstractUnaryop op = 1;</code>
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractUnaryopOrBuilder getOpOrBuilder() {
    return getOp();
  }

  public static final int OPERAND_FIELD_NUMBER = 2;
  private com.giyeok.tython.proto.AbstractExpr operand_;
  /**
   * <code>.com.giyeok.tython.proto.AbstractExpr operand = 2;</code>
   * @return Whether the operand field is set.
   */
  @java.lang.Override
  public boolean hasOperand() {
    return operand_ != null;
  }
  /**
   * <code>.com.giyeok.tython.proto.AbstractExpr operand = 2;</code>
   * @return The operand.
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractExpr getOperand() {
    return operand_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : operand_;
  }
  /**
   * <code>.com.giyeok.tython.proto.AbstractExpr operand = 2;</code>
   */
  @java.lang.Override
  public com.giyeok.tython.proto.AbstractExprOrBuilder getOperandOrBuilder() {
    return getOperand();
  }

  public static final int LINENO_FIELD_NUMBER = 3;
  private int lineno_;
  /**
   * <code>int32 lineno = 3;</code>
   * @return The lineno.
   */
  @java.lang.Override
  public int getLineno() {
    return lineno_;
  }

  public static final int COL_OFFSET_FIELD_NUMBER = 4;
  private int colOffset_;
  /**
   * <code>int32 col_offset = 4;</code>
   * @return The colOffset.
   */
  @java.lang.Override
  public int getColOffset() {
    return colOffset_;
  }

  public static final int END_LINENO_FIELD_NUMBER = 5;
  private int endLineno_;
  /**
   * <code>optional int32 end_lineno = 5;</code>
   * @return Whether the endLineno field is set.
   */
  @java.lang.Override
  public boolean hasEndLineno() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 end_lineno = 5;</code>
   * @return The endLineno.
   */
  @java.lang.Override
  public int getEndLineno() {
    return endLineno_;
  }

  public static final int END_COL_OFFSET_FIELD_NUMBER = 6;
  private int endColOffset_;
  /**
   * <code>optional int32 end_col_offset = 6;</code>
   * @return Whether the endColOffset field is set.
   */
  @java.lang.Override
  public boolean hasEndColOffset() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int32 end_col_offset = 6;</code>
   * @return The endColOffset.
   */
  @java.lang.Override
  public int getEndColOffset() {
    return endColOffset_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (op_ != null) {
      output.writeMessage(1, getOp());
    }
    if (operand_ != null) {
      output.writeMessage(2, getOperand());
    }
    if (lineno_ != 0) {
      output.writeInt32(3, lineno_);
    }
    if (colOffset_ != 0) {
      output.writeInt32(4, colOffset_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(5, endLineno_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(6, endColOffset_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (op_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getOp());
    }
    if (operand_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getOperand());
    }
    if (lineno_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, lineno_);
    }
    if (colOffset_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, colOffset_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, endLineno_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, endColOffset_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.giyeok.tython.proto.UnaryOp)) {
      return super.equals(obj);
    }
    com.giyeok.tython.proto.UnaryOp other = (com.giyeok.tython.proto.UnaryOp) obj;

    if (hasOp() != other.hasOp()) return false;
    if (hasOp()) {
      if (!getOp()
          .equals(other.getOp())) return false;
    }
    if (hasOperand() != other.hasOperand()) return false;
    if (hasOperand()) {
      if (!getOperand()
          .equals(other.getOperand())) return false;
    }
    if (getLineno()
        != other.getLineno()) return false;
    if (getColOffset()
        != other.getColOffset()) return false;
    if (hasEndLineno() != other.hasEndLineno()) return false;
    if (hasEndLineno()) {
      if (getEndLineno()
          != other.getEndLineno()) return false;
    }
    if (hasEndColOffset() != other.hasEndColOffset()) return false;
    if (hasEndColOffset()) {
      if (getEndColOffset()
          != other.getEndColOffset()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasOp()) {
      hash = (37 * hash) + OP_FIELD_NUMBER;
      hash = (53 * hash) + getOp().hashCode();
    }
    if (hasOperand()) {
      hash = (37 * hash) + OPERAND_FIELD_NUMBER;
      hash = (53 * hash) + getOperand().hashCode();
    }
    hash = (37 * hash) + LINENO_FIELD_NUMBER;
    hash = (53 * hash) + getLineno();
    hash = (37 * hash) + COL_OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + getColOffset();
    if (hasEndLineno()) {
      hash = (37 * hash) + END_LINENO_FIELD_NUMBER;
      hash = (53 * hash) + getEndLineno();
    }
    if (hasEndColOffset()) {
      hash = (37 * hash) + END_COL_OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + getEndColOffset();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.giyeok.tython.proto.UnaryOp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.giyeok.tython.proto.UnaryOp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.giyeok.tython.proto.UnaryOp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.giyeok.tython.proto.UnaryOp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.giyeok.tython.proto.UnaryOp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.giyeok.tython.proto.UnaryOp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.giyeok.tython.proto.UnaryOp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.giyeok.tython.proto.UnaryOp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.giyeok.tython.proto.UnaryOp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.giyeok.tython.proto.UnaryOp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.giyeok.tython.proto.UnaryOp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.giyeok.tython.proto.UnaryOp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.giyeok.tython.proto.UnaryOp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.giyeok.tython.proto.UnaryOp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.giyeok.tython.proto.UnaryOp)
      com.giyeok.tython.proto.UnaryOpOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_UnaryOp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_UnaryOp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.giyeok.tython.proto.UnaryOp.class, com.giyeok.tython.proto.UnaryOp.Builder.class);
    }

    // Construct using com.giyeok.tython.proto.UnaryOp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (opBuilder_ == null) {
        op_ = null;
      } else {
        op_ = null;
        opBuilder_ = null;
      }
      if (operandBuilder_ == null) {
        operand_ = null;
      } else {
        operand_ = null;
        operandBuilder_ = null;
      }
      lineno_ = 0;

      colOffset_ = 0;

      endLineno_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      endColOffset_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.giyeok.tython.proto.Python310.internal_static_com_giyeok_tython_proto_UnaryOp_descriptor;
    }

    @java.lang.Override
    public com.giyeok.tython.proto.UnaryOp getDefaultInstanceForType() {
      return com.giyeok.tython.proto.UnaryOp.getDefaultInstance();
    }

    @java.lang.Override
    public com.giyeok.tython.proto.UnaryOp build() {
      com.giyeok.tython.proto.UnaryOp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.giyeok.tython.proto.UnaryOp buildPartial() {
      com.giyeok.tython.proto.UnaryOp result = new com.giyeok.tython.proto.UnaryOp(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (opBuilder_ == null) {
        result.op_ = op_;
      } else {
        result.op_ = opBuilder_.build();
      }
      if (operandBuilder_ == null) {
        result.operand_ = operand_;
      } else {
        result.operand_ = operandBuilder_.build();
      }
      result.lineno_ = lineno_;
      result.colOffset_ = colOffset_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.endLineno_ = endLineno_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.endColOffset_ = endColOffset_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.giyeok.tython.proto.UnaryOp) {
        return mergeFrom((com.giyeok.tython.proto.UnaryOp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.giyeok.tython.proto.UnaryOp other) {
      if (other == com.giyeok.tython.proto.UnaryOp.getDefaultInstance()) return this;
      if (other.hasOp()) {
        mergeOp(other.getOp());
      }
      if (other.hasOperand()) {
        mergeOperand(other.getOperand());
      }
      if (other.getLineno() != 0) {
        setLineno(other.getLineno());
      }
      if (other.getColOffset() != 0) {
        setColOffset(other.getColOffset());
      }
      if (other.hasEndLineno()) {
        setEndLineno(other.getEndLineno());
      }
      if (other.hasEndColOffset()) {
        setEndColOffset(other.getEndColOffset());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.giyeok.tython.proto.UnaryOp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.giyeok.tython.proto.UnaryOp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.giyeok.tython.proto.AbstractUnaryop op_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractUnaryop, com.giyeok.tython.proto.AbstractUnaryop.Builder, com.giyeok.tython.proto.AbstractUnaryopOrBuilder> opBuilder_;
    /**
     * <code>.com.giyeok.tython.proto.AbstractUnaryop op = 1;</code>
     * @return Whether the op field is set.
     */
    public boolean hasOp() {
      return opBuilder_ != null || op_ != null;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractUnaryop op = 1;</code>
     * @return The op.
     */
    public com.giyeok.tython.proto.AbstractUnaryop getOp() {
      if (opBuilder_ == null) {
        return op_ == null ? com.giyeok.tython.proto.AbstractUnaryop.getDefaultInstance() : op_;
      } else {
        return opBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractUnaryop op = 1;</code>
     */
    public Builder setOp(com.giyeok.tython.proto.AbstractUnaryop value) {
      if (opBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        op_ = value;
        onChanged();
      } else {
        opBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractUnaryop op = 1;</code>
     */
    public Builder setOp(
        com.giyeok.tython.proto.AbstractUnaryop.Builder builderForValue) {
      if (opBuilder_ == null) {
        op_ = builderForValue.build();
        onChanged();
      } else {
        opBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractUnaryop op = 1;</code>
     */
    public Builder mergeOp(com.giyeok.tython.proto.AbstractUnaryop value) {
      if (opBuilder_ == null) {
        if (op_ != null) {
          op_ =
            com.giyeok.tython.proto.AbstractUnaryop.newBuilder(op_).mergeFrom(value).buildPartial();
        } else {
          op_ = value;
        }
        onChanged();
      } else {
        opBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractUnaryop op = 1;</code>
     */
    public Builder clearOp() {
      if (opBuilder_ == null) {
        op_ = null;
        onChanged();
      } else {
        op_ = null;
        opBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractUnaryop op = 1;</code>
     */
    public com.giyeok.tython.proto.AbstractUnaryop.Builder getOpBuilder() {
      
      onChanged();
      return getOpFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractUnaryop op = 1;</code>
     */
    public com.giyeok.tython.proto.AbstractUnaryopOrBuilder getOpOrBuilder() {
      if (opBuilder_ != null) {
        return opBuilder_.getMessageOrBuilder();
      } else {
        return op_ == null ?
            com.giyeok.tython.proto.AbstractUnaryop.getDefaultInstance() : op_;
      }
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractUnaryop op = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractUnaryop, com.giyeok.tython.proto.AbstractUnaryop.Builder, com.giyeok.tython.proto.AbstractUnaryopOrBuilder> 
        getOpFieldBuilder() {
      if (opBuilder_ == null) {
        opBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.giyeok.tython.proto.AbstractUnaryop, com.giyeok.tython.proto.AbstractUnaryop.Builder, com.giyeok.tython.proto.AbstractUnaryopOrBuilder>(
                getOp(),
                getParentForChildren(),
                isClean());
        op_ = null;
      }
      return opBuilder_;
    }

    private com.giyeok.tython.proto.AbstractExpr operand_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder> operandBuilder_;
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr operand = 2;</code>
     * @return Whether the operand field is set.
     */
    public boolean hasOperand() {
      return operandBuilder_ != null || operand_ != null;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr operand = 2;</code>
     * @return The operand.
     */
    public com.giyeok.tython.proto.AbstractExpr getOperand() {
      if (operandBuilder_ == null) {
        return operand_ == null ? com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : operand_;
      } else {
        return operandBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr operand = 2;</code>
     */
    public Builder setOperand(com.giyeok.tython.proto.AbstractExpr value) {
      if (operandBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        operand_ = value;
        onChanged();
      } else {
        operandBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr operand = 2;</code>
     */
    public Builder setOperand(
        com.giyeok.tython.proto.AbstractExpr.Builder builderForValue) {
      if (operandBuilder_ == null) {
        operand_ = builderForValue.build();
        onChanged();
      } else {
        operandBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr operand = 2;</code>
     */
    public Builder mergeOperand(com.giyeok.tython.proto.AbstractExpr value) {
      if (operandBuilder_ == null) {
        if (operand_ != null) {
          operand_ =
            com.giyeok.tython.proto.AbstractExpr.newBuilder(operand_).mergeFrom(value).buildPartial();
        } else {
          operand_ = value;
        }
        onChanged();
      } else {
        operandBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr operand = 2;</code>
     */
    public Builder clearOperand() {
      if (operandBuilder_ == null) {
        operand_ = null;
        onChanged();
      } else {
        operand_ = null;
        operandBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr operand = 2;</code>
     */
    public com.giyeok.tython.proto.AbstractExpr.Builder getOperandBuilder() {
      
      onChanged();
      return getOperandFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr operand = 2;</code>
     */
    public com.giyeok.tython.proto.AbstractExprOrBuilder getOperandOrBuilder() {
      if (operandBuilder_ != null) {
        return operandBuilder_.getMessageOrBuilder();
      } else {
        return operand_ == null ?
            com.giyeok.tython.proto.AbstractExpr.getDefaultInstance() : operand_;
      }
    }
    /**
     * <code>.com.giyeok.tython.proto.AbstractExpr operand = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder> 
        getOperandFieldBuilder() {
      if (operandBuilder_ == null) {
        operandBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.giyeok.tython.proto.AbstractExpr, com.giyeok.tython.proto.AbstractExpr.Builder, com.giyeok.tython.proto.AbstractExprOrBuilder>(
                getOperand(),
                getParentForChildren(),
                isClean());
        operand_ = null;
      }
      return operandBuilder_;
    }

    private int lineno_ ;
    /**
     * <code>int32 lineno = 3;</code>
     * @return The lineno.
     */
    @java.lang.Override
    public int getLineno() {
      return lineno_;
    }
    /**
     * <code>int32 lineno = 3;</code>
     * @param value The lineno to set.
     * @return This builder for chaining.
     */
    public Builder setLineno(int value) {
      
      lineno_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 lineno = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLineno() {
      
      lineno_ = 0;
      onChanged();
      return this;
    }

    private int colOffset_ ;
    /**
     * <code>int32 col_offset = 4;</code>
     * @return The colOffset.
     */
    @java.lang.Override
    public int getColOffset() {
      return colOffset_;
    }
    /**
     * <code>int32 col_offset = 4;</code>
     * @param value The colOffset to set.
     * @return This builder for chaining.
     */
    public Builder setColOffset(int value) {
      
      colOffset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 col_offset = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearColOffset() {
      
      colOffset_ = 0;
      onChanged();
      return this;
    }

    private int endLineno_ ;
    /**
     * <code>optional int32 end_lineno = 5;</code>
     * @return Whether the endLineno field is set.
     */
    @java.lang.Override
    public boolean hasEndLineno() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 end_lineno = 5;</code>
     * @return The endLineno.
     */
    @java.lang.Override
    public int getEndLineno() {
      return endLineno_;
    }
    /**
     * <code>optional int32 end_lineno = 5;</code>
     * @param value The endLineno to set.
     * @return This builder for chaining.
     */
    public Builder setEndLineno(int value) {
      bitField0_ |= 0x00000001;
      endLineno_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 end_lineno = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndLineno() {
      bitField0_ = (bitField0_ & ~0x00000001);
      endLineno_ = 0;
      onChanged();
      return this;
    }

    private int endColOffset_ ;
    /**
     * <code>optional int32 end_col_offset = 6;</code>
     * @return Whether the endColOffset field is set.
     */
    @java.lang.Override
    public boolean hasEndColOffset() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 end_col_offset = 6;</code>
     * @return The endColOffset.
     */
    @java.lang.Override
    public int getEndColOffset() {
      return endColOffset_;
    }
    /**
     * <code>optional int32 end_col_offset = 6;</code>
     * @param value The endColOffset to set.
     * @return This builder for chaining.
     */
    public Builder setEndColOffset(int value) {
      bitField0_ |= 0x00000002;
      endColOffset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 end_col_offset = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndColOffset() {
      bitField0_ = (bitField0_ & ~0x00000002);
      endColOffset_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.giyeok.tython.proto.UnaryOp)
  }

  // @@protoc_insertion_point(class_scope:com.giyeok.tython.proto.UnaryOp)
  private static final com.giyeok.tython.proto.UnaryOp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.giyeok.tython.proto.UnaryOp();
  }

  public static com.giyeok.tython.proto.UnaryOp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UnaryOp>
      PARSER = new com.google.protobuf.AbstractParser<UnaryOp>() {
    @java.lang.Override
    public UnaryOp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UnaryOp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UnaryOp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UnaryOp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.giyeok.tython.proto.UnaryOp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

