// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: python3_10.proto

package com.giyeok.tython.proto;

public interface WithOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.giyeok.tython.proto.With)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.giyeok.tython.proto.Withitem items = 1;</code>
   */
  java.util.List<com.giyeok.tython.proto.Withitem> 
      getItemsList();
  /**
   * <code>repeated .com.giyeok.tython.proto.Withitem items = 1;</code>
   */
  com.giyeok.tython.proto.Withitem getItems(int index);
  /**
   * <code>repeated .com.giyeok.tython.proto.Withitem items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .com.giyeok.tython.proto.Withitem items = 1;</code>
   */
  java.util.List<? extends com.giyeok.tython.proto.WithitemOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .com.giyeok.tython.proto.Withitem items = 1;</code>
   */
  com.giyeok.tython.proto.WithitemOrBuilder getItemsOrBuilder(
      int index);

  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 2;</code>
   */
  java.util.List<com.giyeok.tython.proto.AbstractStmt> 
      getBodyList();
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 2;</code>
   */
  com.giyeok.tython.proto.AbstractStmt getBody(int index);
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 2;</code>
   */
  int getBodyCount();
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 2;</code>
   */
  java.util.List<? extends com.giyeok.tython.proto.AbstractStmtOrBuilder> 
      getBodyOrBuilderList();
  /**
   * <code>repeated .com.giyeok.tython.proto.AbstractStmt body = 2;</code>
   */
  com.giyeok.tython.proto.AbstractStmtOrBuilder getBodyOrBuilder(
      int index);

  /**
   * <code>optional string type_comment = 3;</code>
   * @return Whether the typeComment field is set.
   */
  boolean hasTypeComment();
  /**
   * <code>optional string type_comment = 3;</code>
   * @return The typeComment.
   */
  java.lang.String getTypeComment();
  /**
   * <code>optional string type_comment = 3;</code>
   * @return The bytes for typeComment.
   */
  com.google.protobuf.ByteString
      getTypeCommentBytes();

  /**
   * <code>int32 lineno = 4;</code>
   * @return The lineno.
   */
  int getLineno();

  /**
   * <code>int32 col_offset = 5;</code>
   * @return The colOffset.
   */
  int getColOffset();

  /**
   * <code>optional int32 end_lineno = 6;</code>
   * @return Whether the endLineno field is set.
   */
  boolean hasEndLineno();
  /**
   * <code>optional int32 end_lineno = 6;</code>
   * @return The endLineno.
   */
  int getEndLineno();

  /**
   * <code>optional int32 end_col_offset = 7;</code>
   * @return Whether the endColOffset field is set.
   */
  boolean hasEndColOffset();
  /**
   * <code>optional int32 end_col_offset = 7;</code>
   * @return The endColOffset.
   */
  int getEndColOffset();
}
